
const data = [
    {city:"Adair",tree_name:"Acer saccharinum",count:72},
    {city:"Adair",tree_name:"Fraxinus pennsylvanica",count:53},
    {city:"Adair",tree_name:"Acer platanoides",count:27},
    {city:"Adair",tree_name:"Picea pungens",count:22},
    {city:"Adair",tree_name:"Acer saccharum",count:16},
    {city:"Adair",tree_name:"Juglans nigra",count:16},
    {city:"Adair",tree_name:"Malus",count:16},
    {city:"Adair",tree_name:"Acer",count:14},
    {city:"Adair",tree_name:"Syringa",count:11},
    {city:"Adair",tree_name:"Tilia americana",count:9},
    {city:"Adel",tree_name:"Fraxinus pennsylvanica",count:97},
    {city:"Adel",tree_name:"Acer saccharinum",count:89},
    {city:"Adel",tree_name:"Malus",count:57},
    {city:"Adel",tree_name:"Acer nigrum",count:40},
    {city:"Adel",tree_name:"Pyrus",count:39},
    {city:"Adel",tree_name:"Acer platanoides",count:37},
    {city:"Adel",tree_name:"Acer saccharum",count:29},
    {city:"Adel",tree_name:"Ulmus pumila",count:16},
    {city:"Adel",tree_name:"Quercus bicolor",count:14},
    {city:"Adel",tree_name:"Tilia cordata",count:14},
    {city:"Ahuimanu",tree_name:"Lagerstroemia indica",count:7},
    {city:"Ahuimanu",tree_name:"Delonix regia",count:5},
    {city:"Ahuimanu",tree_name:"Harpullia pendula",count:1},
    {city:"Ahuimanu",tree_name:"Plumeria",count:1},
    {city:"Aiea",tree_name:"Albizia saman",count:1},
    {city:"Albuquerque",tree_name:"Ulmus pumila",count:216},
    {city:"Albuquerque",tree_name:"Platanus acerifolia",count:186},
    {city:"Albuquerque",tree_name:"Gleditsia triacanthos",count:159},
    {city:"Albuquerque",tree_name:"Pinus nigra",count:149},
    {city:"Albuquerque",tree_name:"Fraxinus",count:148},
    {city:"Albuquerque",tree_name:"Malus",count:127},
    {city:"Albuquerque",tree_name:"Ulmus",count:107},
    {city:"Albuquerque",tree_name:"Ulmus parvifolia",count:82},
    {city:"Albuquerque",tree_name:"Quercus buckleyi",count:73},
    {city:"Albuquerque",tree_name:"Chilopsis linearis",count:63},
    {city:"Anaheim",tree_name:"Magnolia grandiflora",count:5087},
    {city:"Anaheim",tree_name:"Lagerstroemia indica",count:3538},
    {city:"Anaheim",tree_name:"Washingtonia robusta",count:3515},
    {city:"Anaheim",tree_name:"Cinnamomum camphora",count:2450},
    {city:"Anaheim",tree_name:"Koelreuteria bipinnata",count:2172},
    {city:"Anaheim",tree_name:"Pinus canariensis",count:2157},
    {city:"Anaheim",tree_name:"Jacaranda mimosifolia",count:1647},
    {city:"Anaheim",tree_name:"Syagrus romanzoffianum",count:1551},
    {city:"Anaheim",tree_name:"Liquidambar styraciflua",count:1471},
    {city:"Anaheim",tree_name:"Lophostemon confertus",count:1465},
    {city:"Arlington",tree_name:"Ulmus crassifolia",count:1569},
    {city:"Arlington",tree_name:"Lagerstroemia indica",count:1194},
    {city:"Arlington",tree_name:"Quercus shumardii",count:1139},
    {city:"Arlington",tree_name:"Quercus virginiana",count:1081},
    {city:"Arlington",tree_name:"Cercis canadensis",count:687},
    {city:"Arlington",tree_name:"Quercus muehlenbergii",count:590},
    {city:"Arlington",tree_name:"Pistacia chinensis",count:587},
    {city:"Arlington",tree_name:"Quercus macrocarpa",count:581},
    {city:"Arlington",tree_name:"Taxodium distichum",count:581},
    {city:"Arlington",tree_name:"Quercus stellata",count:558},
    {city:"Atlanta",tree_name:"Cercis canadensis",count:3678},
    {city:"Atlanta",tree_name:"Lagerstroemia",count:2581},
    {city:"Atlanta",tree_name:"Acer buergerianum",count:1742},
    {city:"Atlanta",tree_name:"Lagerstroemia indica",count:1612},
    {city:"Atlanta",tree_name:"Acer rubrum",count:1263},
    {city:"Atlanta",tree_name:"Quercus nuttallii",count:1261},
    {city:"Atlanta",tree_name:"Quercus alba",count:1225},
    {city:"Atlanta",tree_name:"Nyssa sylvatica",count:1151},
    {city:"Atlanta",tree_name:"Cornus florida",count:1041},
    {city:"Atlanta",tree_name:"Carpinus caroliniana",count:851},
    {city:"Aurora",tree_name:"Gleditsia triacanthos",count:10428},
    {city:"Aurora",tree_name:"Tilia",count:6107},
    {city:"Aurora",tree_name:"Fraxinus pennsylvanica",count:5465},
    {city:"Aurora",tree_name:"Acer platanoides",count:4745},
    {city:"Aurora",tree_name:"Acer saccharinum",count:3433},
    {city:"Aurora",tree_name:"Celtis occidentalis",count:2493},
    {city:"Aurora",tree_name:"Tilia americana",count:1668},
    {city:"Aurora",tree_name:"Malus",count:1536},
    {city:"Aurora",tree_name:"Pinus nigra",count:1517},
    {city:"Aurora",tree_name:"Pyrus calleryana",count:1490},
    {city:"Austin",tree_name:"Carya illinoinensis",count:916},
    {city:"Austin",tree_name:"Ulmus crassifolia",count:831},
    {city:"Austin",tree_name:"Quercus virginiana",count:790},
    {city:"Austin",tree_name:"Lagerstroemia indica",count:609},
    {city:"Austin",tree_name:"Quercus fusiformis",count:590},
    {city:"Austin",tree_name:"Quercus shumardii",count:485},
    {city:"Austin",tree_name:"Ulmus americana",count:232},
    {city:"Austin",tree_name:"Taxodium distichum",count:164},
    {city:"Austin",tree_name:"Celtis laevigata",count:163},
    {city:"Austin",tree_name:"Fraxinus texensis",count:112},
    {city:"AvondaleEstates",tree_name:"Parrotia persica",count:27},
    {city:"AvondaleEstates",tree_name:"Cercis canadensis",count:24},
    {city:"AvondaleEstates",tree_name:"Nyssa sylvatica",count:23},
    {city:"AvondaleEstates",tree_name:"Acer buergerianum",count:15},
    {city:"AvondaleEstates",tree_name:"Amelanchier arborea",count:14},
    {city:"AvondaleEstates",tree_name:"Quercus pagoda",count:14},
    {city:"AvondaleEstates",tree_name:"Quercus lyrata",count:13},
    {city:"AvondaleEstates",tree_name:"Styrax japonicus",count:13},
    {city:"AvondaleEstates",tree_name:"Ulmus americana",count:13},
    {city:"AvondaleEstates",tree_name:"Acer saccharum",count:12},
    {city:"Baltimore",tree_name:"Acer rubrum",count:12910},
    {city:"Baltimore",tree_name:"Zelkova serrata",count:6766},
    {city:"Baltimore",tree_name:"Platanus acerifolia",count:6056},
    {city:"Baltimore",tree_name:"Tilia cordata",count:5932},
    {city:"Baltimore",tree_name:"Prunus",count:5817},
    {city:"Baltimore",tree_name:"Pyrus calleryana",count:4747},
    {city:"Baltimore",tree_name:"Acer platanoides",count:3717},
    {city:"Baltimore",tree_name:"Gleditsia triacanthos",count:3289},
    {city:"Baltimore",tree_name:"Quercus phellos",count:3036},
    {city:"Baltimore",tree_name:"Quercus rubra",count:2849},
    {city:"Baxter",tree_name:"Acer saccharum",count:146},
    {city:"Baxter",tree_name:"Acer saccharinum",count:18},
    {city:"Baxter",tree_name:"Juniperus virginiana",count:13},
    {city:"Baxter",tree_name:"Picea pungens",count:11},
    {city:"Baxter",tree_name:"Quercus rubra",count:10},
    {city:"Baxter",tree_name:"Syringa",count:10},
    {city:"Baxter",tree_name:"Acer rubrum",count:8},
    {city:"Baxter",tree_name:"Thuja occidentalis",count:7},
    {city:"Baxter",tree_name:"Fraxinus pennsylvanica",count:5},
    {city:"Baxter",tree_name:"Picea abies",count:5},
    {city:"Bayard",tree_name:"Fraxinus pennsylvanica",count:13},
    {city:"Bayard",tree_name:"Acer saccharinum",count:12},
    {city:"Bayard",tree_name:"Acer saccharum",count:11},
    {city:"Bayard",tree_name:"Acer platanoides",count:9},
    {city:"Bayard",tree_name:"Celtis occidentalis",count:4},
    {city:"Bayard",tree_name:"Gleditsia triacanthos",count:3},
    {city:"Bayard",tree_name:"Juglans nigra",count:3},
    {city:"Bayard",tree_name:"Tilia americana",count:3},
    {city:"Bayard",tree_name:"Platanus occidentalis",count:2},
    {city:"Bayard",tree_name:"Ulmus pumila",count:2},
    {city:"Bondurant",tree_name:"Malus",count:61},
    {city:"Bondurant",tree_name:"Catalpa",count:51},
    {city:"Bondurant",tree_name:"Fraxinus pennsylvanica",count:40},
    {city:"Bondurant",tree_name:"Acer saccharinum",count:34},
    {city:"Bondurant",tree_name:"Pinus sylvestris",count:22},
    {city:"Bondurant",tree_name:"Picea",count:21},
    {city:"Bondurant",tree_name:"Quercus bicolor",count:21},
    {city:"Bondurant",tree_name:"Acer saccharum",count:20},
    {city:"Bondurant",tree_name:"Pyrus",count:17},
    {city:"Bondurant",tree_name:"Acer rubrum",count:15},
    {city:"Boston",tree_name:"Pinus strobus",count:205},
    {city:"Boston",tree_name:"Acer rubrum",count:134},
    {city:"Boston",tree_name:"Quercus rubra",count:105},
    {city:"Boston",tree_name:"Prunus serotina",count:74},
    {city:"Boston",tree_name:"Tree",count:61},
    {city:"Boston",tree_name:"Acer saccharum",count:55},
    {city:"Boston",tree_name:"Tsuga canadensis",count:44},
    {city:"Boston",tree_name:"Pinus rigida",count:40},
    {city:"Boston",tree_name:"Juniperus virginiana",count:37},
    {city:"Boston",tree_name:"Quercus alba",count:30},
    {city:"Bouton",tree_name:"Fraxinus pennsylvanica",count:49},
    {city:"Bouton",tree_name:"Acer saccharinum",count:27},
    {city:"Bouton",tree_name:"Celtis occidentalis",count:18},
    {city:"Bouton",tree_name:"Populus tremuloides",count:14},
    {city:"Bouton",tree_name:"Gleditsia triacanthos",count:6},
    {city:"Bouton",tree_name:"Acer platanoides",count:5},
    {city:"Bouton",tree_name:"Acer nigrum",count:4},
    {city:"Bouton",tree_name:"Fraxinus americana",count:4},
    {city:"Bouton",tree_name:"Juglans nigra",count:3},
    {city:"Bouton",tree_name:"Morus",count:3},
    {city:"Brookhaven",tree_name:"Prunus incam",count:19},
    {city:"Brookhaven",tree_name:"Quercus alba",count:11},
    {city:"Brookhaven",tree_name:"Cercis canadensis",count:8},
    {city:"Brookhaven",tree_name:"Quercus nuttallii",count:8},
    {city:"Brookhaven",tree_name:"Acer rubrum",count:5},
    {city:"Brookhaven",tree_name:"Amelanchier arborea",count:5},
    {city:"Brookhaven",tree_name:"Cornus amomum",count:5},
    {city:"Brookhaven",tree_name:"Liriodendron tulipifera",count:5},
    {city:"Brookhaven",tree_name:"Nyssa sylvatica",count:5},
    {city:"Brookhaven",tree_name:"Magnolia stellata",count:4},
    {city:"Brown Deer",tree_name:"Fraxinus pennsylvanica",count:122},
    {city:"Brown Deer",tree_name:"Acer saccharum",count:90},
    {city:"Brown Deer",tree_name:"Quercus rubra",count:84},
    {city:"Brown Deer",tree_name:"Celtis occidentalis",count:59},
    {city:"Brown Deer",tree_name:"Tilia americana",count:49},
    {city:"Brown Deer",tree_name:"Gleditsia triacanthos",count:31},
    {city:"Brown Deer",tree_name:"Pinus",count:30},
    {city:"Brown Deer",tree_name:"Acer platanoides",count:22},
    {city:"Brown Deer",tree_name:"Malus tschonoskii",count:18},
    {city:"Brown Deer",tree_name:"Fraxinus nigra",count:17},
    {city:"Buffalo",tree_name:"Acer platanoides",count:13265},
    {city:"Buffalo",tree_name:"Tilia cordata",count:9156},
    {city:"Buffalo",tree_name:"Acer saccharinum",count:4725},
    {city:"Buffalo",tree_name:"Malus",count:2731},
    {city:"Buffalo",tree_name:"Acer rubrum",count:2601},
    {city:"Buffalo",tree_name:"Syringa reticulata",count:2373},
    {city:"Buffalo",tree_name:"Acer campestre",count:2370},
    {city:"Buffalo",tree_name:"Gleditsia triacanthos",count:2347},
    {city:"Buffalo",tree_name:"Platanus acerifolia",count:1897},
    {city:"Buffalo",tree_name:"Ulmus carpinifolia",count:1677},
    {city:"CandlerMcAfee",tree_name:"Quercus rubra",count:8},
    {city:"CandlerMcAfee",tree_name:"Quercus nuttallii",count:6},
    {city:"CandlerMcAfee",tree_name:"Tilia americana",count:4},
    {city:"CandlerMcAfee",tree_name:"Cercis canadensis",count:2},
    {city:"CandlerMcAfee",tree_name:"Amelanchier grandiflora",count:1},
    {city:"CandlerMcAfee",tree_name:"Liriodendron tulipifera",count:1},
    {city:"CandlerMcAfee",tree_name:"Nyssa sylvatica",count:1},
    {city:"CandlerMcAfee",tree_name:"Quercus alba",count:1},
    {city:"CandlerMcAfee",tree_name:"Quercus falcata",count:1},
    {city:"CandlerMcAfee",tree_name:"Quercus lyrata",count:1},
    {city:"Cape Coral",tree_name:"Sabal palmetto",count:6632},
    {city:"Cape Coral",tree_name:"Quercus virginiana",count:5727},
    {city:"Cape Coral",tree_name:"Pinus elliottii",count:3298},
    {city:"Cape Coral",tree_name:"Taxodium distichum",count:1724},
    {city:"Cape Coral",tree_name:"Quercus laurifolia",count:903},
    {city:"Cape Coral",tree_name:"Syagrus romanzoffianum",count:817},
    {city:"Cape Coral",tree_name:"Roystonea regia",count:743},
    {city:"Cape Coral",tree_name:"Ilex cassine",count:622},
    {city:"Cape Coral",tree_name:"Wodyetia bifurcata",count:533},
    {city:"Cape Coral",tree_name:"Juniperus silicicola",count:514},
    {city:"Carlisle",tree_name:"Celtis occidentalis",count:64},
    {city:"Carlisle",tree_name:"Fraxinus",count:54},
    {city:"Carlisle",tree_name:"Juglans nigra",count:53},
    {city:"Carlisle",tree_name:"Quercus rubra",count:51},
    {city:"Carlisle",tree_name:"Pinus strobus",count:43},
    {city:"Carlisle",tree_name:"Acer saccharinum",count:33},
    {city:"Carlisle",tree_name:"Malus",count:24},
    {city:"Carlisle",tree_name:"Quercus macrocarpa",count:21},
    {city:"Carlisle",tree_name:"Acer saccharum",count:18},
    {city:"Carlisle",tree_name:"Tilia americana",count:15},
    {city:"Cedarburg",tree_name:"Tilia americana",count:1},
    {city:"Chamblee",tree_name:"Cercis canadensis",count:28},
    {city:"Chamblee",tree_name:"Acer buergerianum",count:16},
    {city:"Chamblee",tree_name:"Quercus lyrata",count:14},
    {city:"Chamblee",tree_name:"Lagerstroemia",count:12},
    {city:"Chamblee",tree_name:"Acer rubrum",count:10},
    {city:"Chamblee",tree_name:"Liriodendron tulipifera",count:9},
    {city:"Chamblee",tree_name:"Ginkgo biloba",count:5},
    {city:"Chamblee",tree_name:"Nyssa sylvatica",count:4},
    {city:"Chamblee",tree_name:"Quercus alba",count:3},
    {city:"Chamblee",tree_name:"Quercus nuttallii",count:3},
    {city:"Clarkston",tree_name:"Cercis canadensis",count:101},
    {city:"Clarkston",tree_name:"Cornus florida",count:79},
    {city:"Clarkston",tree_name:"Prunus L.",count:36},
    {city:"Clarkston",tree_name:"Lagerstroemia indica",count:11},
    {city:"Clarkston",tree_name:"Acer rubrum",count:4},
    {city:"Colfax",tree_name:"Acer saccharinum",count:53},
    {city:"Colfax",tree_name:"Acer saccharum",count:45},
    {city:"Colfax",tree_name:"Fraxinus",count:29},
    {city:"Colfax",tree_name:"Acer",count:28},
    {city:"Colfax",tree_name:"Gleditsia triacanthos",count:13},
    {city:"Colfax",tree_name:"Celtis occidentalis",count:12},
    {city:"Colfax",tree_name:"Ulmus pumila",count:12},
    {city:"Colfax",tree_name:"Malus",count:11},
    {city:"Colfax",tree_name:"Juglans nigra",count:7},
    {city:"Colfax",tree_name:"Acer platanoides",count:6},
    {city:"CollegePark",tree_name:"Quercus nuttallii",count:12},
    {city:"CollegePark",tree_name:"Acer saccharum",count:10},
    {city:"CollegePark",tree_name:"Magnolia",count:8},
    {city:"CollegePark",tree_name:"Acer rubrum",count:7},
    {city:"CollegePark",tree_name:"Chionanthus retusus",count:7},
    {city:"CollegePark",tree_name:"Taxodium distichum",count:6},
    {city:"CollegePark",tree_name:"Carpinus caroliniana",count:5},
    {city:"CollegePark",tree_name:"Quercus phellos",count:5},
    {city:"CollegePark",tree_name:"Ulmus americana",count:5},
    {city:"CollegePark",tree_name:"Cercis canadensis",count:4},
    {city:"Colorado Springs",tree_name:"Pinus ponderosa",count:1924},
    {city:"Colorado Springs",tree_name:"Fraxinus pennsylvanica",count:1844},
    {city:"Colorado Springs",tree_name:"Acer saccharinum",count:952},
    {city:"Colorado Springs",tree_name:"Picea pungens",count:888},
    {city:"Colorado Springs",tree_name:"Ulmus pumila",count:841},
    {city:"Colorado Springs",tree_name:"Ulmus americana",count:686},
    {city:"Colorado Springs",tree_name:"Gleditsia triacanthos",count:559},
    {city:"Colorado Springs",tree_name:"Populus",count:526},
    {city:"Colorado Springs",tree_name:"Acer platanoides",count:495},
    {city:"Colorado Springs",tree_name:"Pinus edulis",count:397},
    {city:"Columbus",tree_name:"Fraxinus pennsylvanica",count:9402},
    {city:"Columbus",tree_name:"Pyrus calleryana",count:9245},
    {city:"Columbus",tree_name:"Acer rubrum",count:8657},
    {city:"Columbus",tree_name:"Acer saccharum",count:7512},
    {city:"Columbus",tree_name:"Gleditsia triacanthos",count:7090},
    {city:"Columbus",tree_name:"Malus",count:6924},
    {city:"Columbus",tree_name:"Fraxinus americana",count:6742},
    {city:"Columbus",tree_name:"Acer freemanii",count:5664},
    {city:"Columbus",tree_name:"Acer platanoides",count:4549},
    {city:"Columbus",tree_name:"Tilia cordata",count:4102},
    {city:"Coon Rapids",tree_name:"Fraxinus pennsylvanica",count:159},
    {city:"Coon Rapids",tree_name:"Acer platanoides",count:88},
    {city:"Coon Rapids",tree_name:"Acer saccharinum",count:65},
    {city:"Coon Rapids",tree_name:"Quercus rubra",count:40},
    {city:"Coon Rapids",tree_name:"Tilia cordata",count:34},
    {city:"Coon Rapids",tree_name:"Acer saccharum",count:26},
    {city:"Coon Rapids",tree_name:"Malus",count:23},
    {city:"Coon Rapids",tree_name:"Gleditsia triacanthos",count:19},
    {city:"Coon Rapids",tree_name:"Juglans nigra",count:16},
    {city:"Coon Rapids",tree_name:"Picea",count:16},
    {city:"Cudahy",tree_name:"Gleditsia triacanthos",count:63},
    {city:"Cudahy",tree_name:"Tilia americana",count:41},
    {city:"Cudahy",tree_name:"Acer saccharinum",count:36},
    {city:"Cudahy",tree_name:"Acer saccharum",count:33},
    {city:"Cudahy",tree_name:"Fraxinus pennsylvanica",count:32},
    {city:"Cudahy",tree_name:"Carya ovata",count:27},
    {city:"Cudahy",tree_name:"Acer platanoides",count:22},
    {city:"Cudahy",tree_name:"Fraxinus americana",count:22},
    {city:"Cudahy",tree_name:"Quercus rubra",count:18},
    {city:"Cudahy",tree_name:"Syringa reticulata",count:11},
    {city:"Dallas",tree_name:"Quercus shumardii",count:6},
    {city:"Dallas",tree_name:"Quercus virginiana",count:6},
    {city:"Dallas",tree_name:"Carya illinoinensis",count:5},
    {city:"Dallas",tree_name:"Pyrus calleryana",count:5},
    {city:"Dallas",tree_name:"Quercus stellata",count:5},
    {city:"Dallas",tree_name:"Ulmus americana",count:5},
    {city:"Dallas",tree_name:"Ulmus crassifolia",count:5},
    {city:"Dallas",tree_name:"Celtis occidentalis",count:4},
    {city:"Dallas",tree_name:"Lagerstroemia indica",count:4},
    {city:"Dallas",tree_name:"Liquidambar styraciflua",count:4},
    {city:"Dallas Center",tree_name:"Fraxinus pennsylvanica",count:148},
    {city:"Dallas Center",tree_name:"Acer saccharinum",count:103},
    {city:"Dallas Center",tree_name:"Acer saccharum",count:94},
    {city:"Dallas Center",tree_name:"Acer platanoides",count:83},
    {city:"Dallas Center",tree_name:"Pinus strobus",count:50},
    {city:"Dallas Center",tree_name:"Malus",count:41},
    {city:"Dallas Center",tree_name:"Quercus rubra",count:33},
    {city:"Dallas Center",tree_name:"Acer rubrum",count:25},
    {city:"Dallas Center",tree_name:"Quercus macrocarpa",count:24},
    {city:"Dallas Center",tree_name:"Celtis occidentalis",count:18},
    {city:"De Soto",tree_name:"Juglans nigra",count:73},
    {city:"De Soto",tree_name:"Acer negundo",count:12},
    {city:"De Soto",tree_name:"Ulmus pumila",count:12},
    {city:"De Soto",tree_name:"Fraxinus pennsylvanica",count:9},
    {city:"De Soto",tree_name:"Acer saccharinum",count:6},
    {city:"De Soto",tree_name:"Acer saccharum",count:5},
    {city:"De Soto",tree_name:"Fraxinus",count:5},
    {city:"De Soto",tree_name:"Platanus occidentalis",count:5},
    {city:"De Soto",tree_name:"Malus",count:4},
    {city:"De Soto",tree_name:"Populus deltoides",count:4},
    {city:"Decatur",tree_name:"Cercis canadensis",count:221},
    {city:"Decatur",tree_name:"Quercus alba",count:100},
    {city:"Decatur",tree_name:"Nyssa sylvatica",count:76},
    {city:"Decatur",tree_name:"Cornus florida",count:67},
    {city:"Decatur",tree_name:"Magnolia",count:56},
    {city:"Decatur",tree_name:"Ilex opaca",count:54},
    {city:"Decatur",tree_name:"Malus",count:50},
    {city:"Decatur",tree_name:"Carpinus caroliniana",count:48},
    {city:"Decatur",tree_name:"Acer rubrum",count:45},
    {city:"Decatur",tree_name:"Magnolia loebneri",count:42},
    {city:"Denver",tree_name:"Fraxinus pennsylvanica",count:25736},
    {city:"Denver",tree_name:"Gleditsia triacanthos",count:24178},
    {city:"Denver",tree_name:"Tilia cordata",count:12961},
    {city:"Denver",tree_name:"Acer saccharinum",count:12735},
    {city:"Denver",tree_name:"Fraxinus americana",count:11922},
    {city:"Denver",tree_name:"Ulmus pumila",count:10671},
    {city:"Denver",tree_name:"Acer freemanii",count:9780},
    {city:"Denver",tree_name:"Malus sylvestris",count:9240},
    {city:"Denver",tree_name:"Celtis occidentalis",count:9060},
    {city:"Denver",tree_name:"Acer platanoides",count:7945},
    {city:"Des Moines",tree_name:"Gymnocladus dioicus",count:4},
    {city:"Des Moines",tree_name:"Quercus",count:4},
    {city:"Des Moines",tree_name:"Quercus alba",count:4},
    {city:"Des Moines",tree_name:"Ulmus americana",count:4},
    {city:"Des Moines",tree_name:"Malus",count:3},
    {city:"Des Moines",tree_name:"Cladrastis kentukea",count:2},
    {city:"Des Moines",tree_name:"Quercus coccinea",count:2},
    {city:"Detroit",tree_name:"Salix",count:1735},
    {city:"Detroit",tree_name:"Populus",count:1276},
    {city:"Detroit",tree_name:"Acer rubrum",count:1183},
    {city:"Detroit",tree_name:"Ulmus",count:981},
    {city:"Detroit",tree_name:"Platanus acerifolia",count:980},
    {city:"Detroit",tree_name:"Celtis occidentalis",count:852},
    {city:"Detroit",tree_name:"Malus",count:706},
    {city:"Detroit",tree_name:"Quercus bicolor",count:702},
    {city:"Detroit",tree_name:"Liriodendron tulipifera",count:622},
    {city:"Detroit",tree_name:"Zelkova serrata",count:580},
    {city:"Dexter",tree_name:"Malus",count:31},
    {city:"Dexter",tree_name:"Fraxinus",count:29},
    {city:"Dexter",tree_name:"Acer saccharum",count:25},
    {city:"Dexter",tree_name:"Acer saccharinum",count:19},
    {city:"Dexter",tree_name:"Acer platanoides",count:11},
    {city:"Dexter",tree_name:"Fraxinus pennsylvanica",count:11},
    {city:"Dexter",tree_name:"Acer",count:10},
    {city:"Dexter",tree_name:"Gleditsia triacanthos",count:9},
    {city:"Dexter",tree_name:"Acer rubrum",count:8},
    {city:"Dexter",tree_name:"Celtis occidentalis",count:6},
    {city:"Doraville",tree_name:"Nyssa sylvatica",count:56},
    {city:"Doraville",tree_name:"Cercis canadensis",count:15},
    {city:"Doraville",tree_name:"Quercus alba",count:11},
    {city:"Doraville",tree_name:"Magnolia",count:9},
    {city:"Doraville",tree_name:"Quercus falcata",count:8},
    {city:"Doraville",tree_name:"Lagerstroemia L.",count:7},
    {city:"Doraville",tree_name:"Acer buergerianum",count:6},
    {city:"Doraville",tree_name:"Lagerstroemia indica",count:4},
    {city:"Doraville",tree_name:"Taxodium distichum",count:3},
    {city:"Doraville",tree_name:"Ulmus americana",count:3},
    {city:"Dunwoody",tree_name:"Cercis canadensis",count:111},
    {city:"Dunwoody",tree_name:"Juniperus virginiana",count:79},
    {city:"Dunwoody",tree_name:"Cornus florida",count:54},
    {city:"Dunwoody",tree_name:"Ilex opaca",count:42},
    {city:"Dunwoody",tree_name:"Nyssa sylvatica",count:39},
    {city:"Dunwoody",tree_name:"Pinus palustris",count:35},
    {city:"Dunwoody",tree_name:"Quercus shumardii",count:35},
    {city:"Dunwoody",tree_name:"Ostrya virginiana",count:33},
    {city:"Dunwoody",tree_name:"Acer rubrum",count:32},
    {city:"Dunwoody",tree_name:"Cryptomeria japonica",count:32},
    {city:"Durham",tree_name:"Lagerstroemia",count:3103},
    {city:"Durham",tree_name:"Quercus phellos",count:2777},
    {city:"Durham",tree_name:"Acer buergerianum",count:1027},
    {city:"Durham",tree_name:"Acer rubrum",count:718},
    {city:"Durham",tree_name:"Ulmus parvifolia",count:573},
    {city:"Durham",tree_name:"Cercis canadensis",count:537},
    {city:"Durham",tree_name:"Ulmus americana",count:375},
    {city:"Durham",tree_name:"Pistacia chinensis",count:363},
    {city:"Durham",tree_name:"Quercus lyrata",count:326},
    {city:"Durham",tree_name:"Ginkgo biloba",count:261},
    {city:"Earlham",tree_name:"Malus",count:151},
    {city:"Earlham",tree_name:"Acer saccharum",count:118},
    {city:"Earlham",tree_name:"Fraxinus pennsylvanica",count:54},
    {city:"Earlham",tree_name:"Acer rubrum",count:35},
    {city:"Earlham",tree_name:"Acer saccharinum",count:26},
    {city:"Earlham",tree_name:"Pyrus",count:26},
    {city:"Earlham",tree_name:"Acer platanoides",count:25},
    {city:"Earlham",tree_name:"Celtis occidentalis",count:24},
    {city:"Earlham",tree_name:"Quercus rubra",count:18},
    {city:"Earlham",tree_name:"Fraxinus americana",count:16},
    {city:"EastPoint",tree_name:"Lagerstroemia",count:84},
    {city:"EastPoint",tree_name:"Acer rubrum",count:48},
    {city:"EastPoint",tree_name:"Parrotia persica",count:41},
    {city:"EastPoint",tree_name:"Cercis canadensis",count:35},
    {city:"EastPoint",tree_name:"Quercus nuttallii",count:33},
    {city:"EastPoint",tree_name:"Acer buergerianum",count:25},
    {city:"EastPoint",tree_name:"Magnolia",count:24},
    {city:"EastPoint",tree_name:"Quercus falcata",count:21},
    {city:"EastPoint",tree_name:"Nyssa sylvatica",count:19},
    {city:"EastPoint",tree_name:"Ulmus americana",count:19},
    {city:"Elkhart",tree_name:"Acer saccharinum",count:28},
    {city:"Elkhart",tree_name:"Fraxinus pennsylvanica",count:17},
    {city:"Elkhart",tree_name:"Quercus macrocarpa",count:16},
    {city:"Elkhart",tree_name:"Malus",count:12},
    {city:"Elkhart",tree_name:"Acer",count:10},
    {city:"Elkhart",tree_name:"Acer saccharum",count:7},
    {city:"Elkhart",tree_name:"Picea",count:7},
    {city:"Elkhart",tree_name:"Acer platanoides",count:4},
    {city:"Elkhart",tree_name:"Celtis occidentalis",count:3},
    {city:"Elkhart",tree_name:"Pinus strobus",count:3},
    {city:"Fox Point",tree_name:"Thuja occidentalis",count:25},
    {city:"Fox Point",tree_name:"Aesculus hippocastanum",count:19},
    {city:"Fox Point",tree_name:"Fraxinus pennsylvanica",count:19},
    {city:"Fox Point",tree_name:"Pinus resinosa",count:11},
    {city:"Fox Point",tree_name:"Quercus rubra",count:11},
    {city:"Fox Point",tree_name:"Fraxinus americana",count:10},
    {city:"Fox Point",tree_name:"Picea glauca",count:10},
    {city:"Fox Point",tree_name:"Tilia americana",count:9},
    {city:"Fox Point",tree_name:"Acer saccharinum",count:7},
    {city:"Fox Point",tree_name:"Picea",count:7},
    {city:"Franklin",tree_name:"Quercus rubra",count:57},
    {city:"Franklin",tree_name:"Gleditsia triacanthos",count:27},
    {city:"Franklin",tree_name:"Malus tschonoskii",count:24},
    {city:"Franklin",tree_name:"Acer saccharum",count:23},
    {city:"Franklin",tree_name:"Fraxinus americana",count:23},
    {city:"Franklin",tree_name:"Juglans nigra",count:22},
    {city:"Franklin",tree_name:"Pinus resinosa",count:18},
    {city:"Franklin",tree_name:"Fraxinus pennsylvanica",count:13},
    {city:"Franklin",tree_name:"Tilia americana",count:11},
    {city:"Franklin",tree_name:"Acer ginnala",count:8},
    {city:"Fresno",tree_name:"Cercis canadensis",count:2},
    {city:"Fresno",tree_name:"Lagerstroemia indica",count:2},
    {city:"Fresno",tree_name:"Acer palmatum",count:1},
    {city:"Fresno",tree_name:"Acer rubrum",count:1},
    {city:"Fresno",tree_name:"Alnus rhombifolia",count:1},
    {city:"Fresno",tree_name:"Betula pendula",count:1},
    {city:"Fresno",tree_name:"Callistemon pallidus",count:1},
    {city:"Fresno",tree_name:"Cedrus atlantica",count:1},
    {city:"Fresno",tree_name:"Cedrus deodara",count:1},
    {city:"Fresno",tree_name:"Celtis occidentalis",count:1},
    {city:"Garden Grove",tree_name:"Lagerstroemia indica",count:2358},
    {city:"Garden Grove",tree_name:"Lophostemon confertus",count:1643},
    {city:"Garden Grove",tree_name:"Cupaniopsis anacardioides",count:1438},
    {city:"Garden Grove",tree_name:"Pinus canariensis",count:1049},
    {city:"Garden Grove",tree_name:"Syagrus romanzoffianum",count:897},
    {city:"Garden Grove",tree_name:"Pyrus kawakamii",count:710},
    {city:"Garden Grove",tree_name:"Magnolia grandiflora",count:696},
    {city:"Garden Grove",tree_name:"Jacaranda acutifolia",count:668},
    {city:"Garden Grove",tree_name:"Washingtonia robusta",count:596},
    {city:"Garden Grove",tree_name:"Platanus acerifolia",count:593},
    {city:"Glendale",tree_name:"Fraxinus pennsylvanica",count:442},
    {city:"Glendale",tree_name:"Acer saccharum",count:186},
    {city:"Glendale",tree_name:"Acer platanoides",count:175},
    {city:"Glendale",tree_name:"Quercus rubra",count:116},
    {city:"Glendale",tree_name:"Acer saccharinum",count:111},
    {city:"Glendale",tree_name:"Celtis occidentalis",count:83},
    {city:"Glendale",tree_name:"Juglans nigra",count:77},
    {city:"Glendale",tree_name:"Fraxinus americana",count:57},
    {city:"Glendale",tree_name:"Gleditsia triacanthos",count:49},
    {city:"Glendale",tree_name:"Malus tschonoskii",count:49},
    {city:"Grand Rapids",tree_name:"Gleditsia triacanthos",count:12},
    {city:"Grand Rapids",tree_name:"Picea pungens",count:10},
    {city:"Grand Rapids",tree_name:"Acer platanoides",count:9},
    {city:"Grand Rapids",tree_name:"Morus alba",count:9},
    {city:"Grand Rapids",tree_name:"Zelkova serrata",count:7},
    {city:"Grand Rapids",tree_name:"Acer freemanii",count:6},
    {city:"Grand Rapids",tree_name:"Acer negundo",count:6},
    {city:"Grand Rapids",tree_name:"Acer pseudoplatanus",count:6},
    {city:"Grand Rapids",tree_name:"Acer rubrum",count:6},
    {city:"Grand Rapids",tree_name:"Acer saccharinum",count:6},
    {city:"Granger",tree_name:"Fraxinus pennsylvanica",count:46},
    {city:"Granger",tree_name:"Acer saccharinum",count:21},
    {city:"Granger",tree_name:"Malus",count:15},
    {city:"Granger",tree_name:"Acer platanoides",count:12},
    {city:"Granger",tree_name:"Quercus rubra",count:11},
    {city:"Granger",tree_name:"Quercus bicolor",count:9},
    {city:"Granger",tree_name:"Celtis occidentalis",count:7},
    {city:"Granger",tree_name:"Pyrus",count:7},
    {city:"Granger",tree_name:"Acer rubrum",count:6},
    {city:"Granger",tree_name:"Betula",count:6},
    {city:"Greendale",tree_name:"Fraxinus pennsylvanica",count:31},
    {city:"Greendale",tree_name:"Celtis occidentalis",count:27},
    {city:"Greendale",tree_name:"Pinus resinosa",count:17},
    {city:"Greendale",tree_name:"Pinus sylvestris",count:16},
    {city:"Greendale",tree_name:"Malus tschonoskii",count:14},
    {city:"Greendale",tree_name:"Tilia americana",count:14},
    {city:"Greendale",tree_name:"Acer saccharum",count:12},
    {city:"Greendale",tree_name:"Quercus rubra",count:12},
    {city:"Greendale",tree_name:"Crataegus",count:10},
    {city:"Greendale",tree_name:"Quercus macrocarpa",count:10},
    {city:"Greenfield",tree_name:"Acer saccharum",count:61},
    {city:"Greenfield",tree_name:"Fraxinus pennsylvanica",count:26},
    {city:"Greenfield",tree_name:"Quercus rubra",count:26},
    {city:"Greenfield",tree_name:"Acer platanoides",count:25},
    {city:"Greenfield",tree_name:"Quercus alba",count:25},
    {city:"Greenfield",tree_name:"Gleditsia triacanthos",count:22},
    {city:"Greenfield",tree_name:"Celtis occidentalis",count:18},
    {city:"Greenfield",tree_name:"Crataegus",count:18},
    {city:"Greenfield",tree_name:"Malus tschonoskii",count:18},
    {city:"Greenfield",tree_name:"Tilia americana",count:17},
    {city:"Greensboro",tree_name:"Lagerstroemia",count:713},
    {city:"Greensboro",tree_name:"Quercus phellos",count:523},
    {city:"Greensboro",tree_name:"Carya illinoinensis",count:437},
    {city:"Greensboro",tree_name:"Ulmus",count:405},
    {city:"Greensboro",tree_name:"Celtis occidentalis",count:295},
    {city:"Greensboro",tree_name:"Cornus florida",count:248},
    {city:"Greensboro",tree_name:"Acer saccharum",count:238},
    {city:"Greensboro",tree_name:"Morus",count:222},
    {city:"Greensboro",tree_name:"Acer rubrum",count:221},
    {city:"Greensboro",tree_name:"Juglans nigra",count:220},
    {city:"Guthrie Center",tree_name:"Acer saccharum",count:68},
    {city:"Guthrie Center",tree_name:"Fraxinus pennsylvanica",count:38},
    {city:"Guthrie Center",tree_name:"Acer saccharinum",count:27},
    {city:"Guthrie Center",tree_name:"Acer platanoides",count:20},
    {city:"Guthrie Center",tree_name:"Celtis occidentalis",count:17},
    {city:"Guthrie Center",tree_name:"Quercus palustris",count:11},
    {city:"Guthrie Center",tree_name:"Juglans nigra",count:8},
    {city:"Guthrie Center",tree_name:"Tilia cordata",count:7},
    {city:"Guthrie Center",tree_name:"Malus",count:6},
    {city:"Guthrie Center",tree_name:"Quercus rubra",count:4},
    {city:"Hales Corners",tree_name:"Acer saccharum",count:43},
    {city:"Hales Corners",tree_name:"Fraxinus pennsylvanica",count:43},
    {city:"Hales Corners",tree_name:"Gleditsia triacanthos",count:35},
    {city:"Hales Corners",tree_name:"Juglans nigra",count:29},
    {city:"Hales Corners",tree_name:"Acer platanoides",count:24},
    {city:"Hales Corners",tree_name:"Celtis occidentalis",count:21},
    {city:"Hales Corners",tree_name:"Malus tschonoskii",count:20},
    {city:"Hales Corners",tree_name:"Quercus rubra",count:17},
    {city:"Hales Corners",tree_name:"Crataegus",count:16},
    {city:"Hales Corners",tree_name:"Fraxinus americana",count:16},
    {city:"Hapeville",tree_name:"Acer buergerianum",count:51},
    {city:"Hapeville",tree_name:"Ulmus americana",count:31},
    {city:"Hapeville",tree_name:"Lagerstroemia indica",count:30},
    {city:"Hapeville",tree_name:"Quercus nuttallii",count:19},
    {city:"Hapeville",tree_name:"Taxodium distichum",count:17},
    {city:"Hapeville",tree_name:"Quercus shumardii",count:16},
    {city:"Hapeville",tree_name:"Cercis canadensis",count:14},
    {city:"Hapeville",tree_name:"Quercus alba",count:13},
    {city:"Hapeville",tree_name:"Magnolia",count:9},
    {city:"Hapeville",tree_name:"Magnolia grandiflora",count:9},
    {city:"Hartford",tree_name:"Acer saccharinum",count:4},
    {city:"Hartford",tree_name:"Celtis occidentalis",count:4},
    {city:"Hartford",tree_name:"Acer platanoides",count:2},
    {city:"Hartford",tree_name:"Juglans nigra",count:2},
    {city:"Hartford",tree_name:"Morus",count:2},
    {city:"Hartford",tree_name:"Picea pungens",count:2},
    {city:"Hartford",tree_name:"Quercus macrocarpa",count:2},
    {city:"Hartford",tree_name:"Ulmus pumila",count:2},
    {city:"Hartford",tree_name:"Acer ginnala",count:1},
    {city:"Hartford",tree_name:"Acer rubrum",count:1},
    {city:"Heeia",tree_name:"Lagerstroemia indica",count:1},
    {city:"Honolulu",tree_name:"Albizia saman",count:718},
    {city:"Honolulu",tree_name:"Cocos nucifera",count:635},
    {city:"Honolulu",tree_name:"Cassia nealiae",count:576},
    {city:"Honolulu",tree_name:"Tabebuia heterophylla",count:421},
    {city:"Honolulu",tree_name:"Acacia confusa",count:332},
    {city:"Honolulu",tree_name:"Adonidia merrillii",count:243},
    {city:"Honolulu",tree_name:"Pritchardia pacifica",count:186},
    {city:"Honolulu",tree_name:"Ficus microcarpa",count:179},
    {city:"Honolulu",tree_name:"Cassine orientalis",count:163},
    {city:"Honolulu",tree_name:"Tabebuia berteroi",count:161},
    {city:"Houston",tree_name:"Lagerstroemia indica",count:44320},
    {city:"Houston",tree_name:"Quercus virginiana",count:44059},
    {city:"Houston",tree_name:"Celtis occidentalis",count:13013},
    {city:"Houston",tree_name:"Quercus nigra",count:10804},
    {city:"Houston",tree_name:"Triadica sebifera",count:9561},
    {city:"Houston",tree_name:"Pinus taeda",count:8893},
    {city:"Houston",tree_name:"Carya illinoinensis",count:6129},
    {city:"Houston",tree_name:"Washingtonia robusta",count:5466},
    {city:"Houston",tree_name:"Fraxinus velutina",count:4829},
    {city:"Houston",tree_name:"Magnolia grandiflora",count:4297},
    {city:"Huntington Beach",tree_name:"Syagrus romanzoffianum",count:4681},
    {city:"Huntington Beach",tree_name:"Washingtonia robusta",count:4037},
    {city:"Huntington Beach",tree_name:"Lagerstroemia indica",count:3896},
    {city:"Huntington Beach",tree_name:"Eucalyptus camaldulensis",count:2574},
    {city:"Huntington Beach",tree_name:"Archontophoenix cunninghamiana",count:1665},
    {city:"Huntington Beach",tree_name:"Cercis canadensis",count:1502},
    {city:"Huntington Beach",tree_name:"Lophostemon confertus",count:1453},
    {city:"Huntington Beach",tree_name:"Cupaniopsis anacardioides",count:1431},
    {city:"Huntington Beach",tree_name:"Pinus canariensis",count:1352},
    {city:"Huntington Beach",tree_name:"Pyrus calleryana",count:1233},
    {city:"Indianapolis",tree_name:"Abies fraseri",count:6},
    {city:"Indianapolis",tree_name:"Acer",count:6},
    {city:"Indianapolis",tree_name:"Acer negundo",count:6},
    {city:"Indianapolis",tree_name:"Acer nigrum",count:6},
    {city:"Indianapolis",tree_name:"Acer platanoides",count:6},
    {city:"Indianapolis",tree_name:"Acer rubrum",count:6},
    {city:"Indianapolis",tree_name:"Acer saccharum",count:6},
    {city:"Indianapolis",tree_name:"Aesculus",count:6},
    {city:"Indianapolis",tree_name:"Aesculus glabra",count:6},
    {city:"Indianapolis",tree_name:"Ailanthus altissima",count:6},
    {city:"Irvine",tree_name:"Eucalyptus globulus",count:349},
    {city:"Irvine",tree_name:"Pinus canariensis",count:289},
    {city:"Irvine",tree_name:"Eucalyptus maculata",count:256},
    {city:"Irvine",tree_name:"Platanus racemosa",count:225},
    {city:"Irvine",tree_name:"Pinus halepensis",count:190},
    {city:"Irvine",tree_name:"Pinus brutia",count:189},
    {city:"Irvine",tree_name:"Tristaniopsis Brongn.",count:186},
    {city:"Irvine",tree_name:"Eucalyptus sideroxylon",count:184},
    {city:"Irvine",tree_name:"Eucalyptus citriodora",count:182},
    {city:"Irvine",tree_name:"Jacaranda mimosifolia",count:171},
    {city:"Jersey City",tree_name:"Thuja occidentalis",count:111},
    {city:"Jersey City",tree_name:"Quercus rubra",count:101},
    {city:"Jersey City",tree_name:"Quercus bicolor",count:92},
    {city:"Jersey City",tree_name:"Tilia cordata",count:78},
    {city:"Jersey City",tree_name:"Acer rubrum",count:63},
    {city:"Jersey City",tree_name:"Platanus occidentalis",count:62},
    {city:"Jersey City",tree_name:"Acer saccharum",count:56},
    {city:"Jersey City",tree_name:"Juniperus virginiana",count:33},
    {city:"Jersey City",tree_name:"Juniperus chinensis",count:22},
    {city:"Jersey City",tree_name:"Amelanchier canadensis",count:17},
    {city:"Kailua",tree_name:"Adonidia merrillii",count:983},
    {city:"Kailua",tree_name:"Cocos nucifera",count:981},
    {city:"Kailua",tree_name:"Tabebuia heterophylla",count:373},
    {city:"Kailua",tree_name:"Casuarina equisetifolia",count:345},
    {city:"Kailua",tree_name:"Conocarpus erectus",count:251},
    {city:"Kailua",tree_name:"Cassia nealiae",count:219},
    {city:"Kailua",tree_name:"Filicium decipiens",count:178},
    {city:"Kailua",tree_name:"Cordia sebestena",count:170},
    {city:"Kailua",tree_name:"Calophyllum inophyllum",count:124},
    {city:"Kailua",tree_name:"Ilex paraguariensis",count:119},
    {city:"Kaneohe",tree_name:"Adonidia merrillii",count:297},
    {city:"Kaneohe",tree_name:"Cassia nealiae",count:154},
    {city:"Kaneohe",tree_name:"Tabebuia heterophylla",count:145},
    {city:"Kaneohe",tree_name:"Lagerstroemia indica",count:129},
    {city:"Kaneohe",tree_name:"Cocos nucifera",count:104},
    {city:"Kaneohe",tree_name:"Filicium decipiens",count:77},
    {city:"Kaneohe",tree_name:"Arecaceae",count:76},
    {city:"Kaneohe",tree_name:"Chrysophyllum oliviforme",count:71},
    {city:"Kaneohe",tree_name:"Conocarpus erectus",count:64},
    {city:"Kaneohe",tree_name:"Melaleuca quinquenervia",count:60},
    {city:"Kellogg",tree_name:"Juglans nigra",count:31},
    {city:"Kellogg",tree_name:"Acer saccharinum",count:22},
    {city:"Kellogg",tree_name:"Fraxinus pennsylvanica",count:16},
    {city:"Kellogg",tree_name:"Acer saccharum",count:8},
    {city:"Kellogg",tree_name:"Picea",count:8},
    {city:"Kellogg",tree_name:"Gleditsia triacanthos",count:5},
    {city:"Kellogg",tree_name:"Celtis occidentalis",count:4},
    {city:"Kellogg",tree_name:"Juniperus virginiana",count:3},
    {city:"Kellogg",tree_name:"Ulmus pumila",count:3},
    {city:"Kellogg",tree_name:"Acer platanoides",count:2},
    {city:"Knoxville",tree_name:"Acer rubrum",count:683},
    {city:"Knoxville",tree_name:"Cornus florida",count:602},
    {city:"Knoxville",tree_name:"Acer saccharum",count:594},
    {city:"Knoxville",tree_name:"Lagerstroemia indica",count:517},
    {city:"Knoxville",tree_name:"Cercis canadensis",count:323},
    {city:"Knoxville",tree_name:"Quercus phellos",count:321},
    {city:"Knoxville",tree_name:"Celtis occidentalis",count:282},
    {city:"Knoxville",tree_name:"Pinus strobus",count:199},
    {city:"Knoxville",tree_name:"Quercus palustris",count:184},
    {city:"Knoxville",tree_name:"Acer saccharinum",count:172},
    {city:"Las Vegas",tree_name:"Pinus brutia",count:5888},
    {city:"Las Vegas",tree_name:"Fraxinus velutina",count:4480},
    {city:"Las Vegas",tree_name:"Washingtonia robusta",count:1842},
    {city:"Las Vegas",tree_name:"Acacia stenophylla",count:1483},
    {city:"Las Vegas",tree_name:"Vitex agnus-castus",count:1478},
    {city:"Las Vegas",tree_name:"Prosopis chilensis",count:1278},
    {city:"Las Vegas",tree_name:"Fraxinus angustifolia",count:1135},
    {city:"Las Vegas",tree_name:"Chitalpa tashkentensis",count:1050},
    {city:"Las Vegas",tree_name:"Chilopsis linearis",count:1020},
    {city:"Las Vegas",tree_name:"Phoenix dactylifera",count:941},
    {city:"Lithonia",tree_name:"Quercus alba",count:3},
    {city:"Lithonia",tree_name:"Acer rubrum",count:1},
    {city:"Lithonia",tree_name:"Cercis canadensis",count:1},
    {city:"Los Angeles",tree_name:"Magnolia grandiflora",count:24974},
    {city:"Los Angeles",tree_name:"Lagerstroemia indica",count:23897},
    {city:"Los Angeles",tree_name:"Liquidambar styraciflua",count:23087},
    {city:"Los Angeles",tree_name:"Washingtonia robusta",count:22371},
    {city:"Los Angeles",tree_name:"Ficus microcarpa",count:17238},
    {city:"Los Angeles",tree_name:"Cinnamomum camphora",count:12769},
    {city:"Los Angeles",tree_name:"Platanus acerifolia",count:11293},
    {city:"Los Angeles",tree_name:"Ulmus parvifolia",count:10978},
    {city:"Los Angeles",tree_name:"Jacaranda acutifolia",count:10837},
    {city:"Los Angeles",tree_name:"Fraxinus velutina",count:10044},
    {city:"Louisville",tree_name:"Acer saccharum",count:1810},
    {city:"Louisville",tree_name:"Quercus palustris",count:1678},
    {city:"Louisville",tree_name:"Acer rubrum",count:1536},
    {city:"Louisville",tree_name:"Fraxinus pennsylvanica",count:1404},
    {city:"Louisville",tree_name:"Celtis occidentalis",count:1086},
    {city:"Louisville",tree_name:"Liriodendron tulipifera",count:994},
    {city:"Louisville",tree_name:"Liquidambar styraciflua",count:833},
    {city:"Louisville",tree_name:"Quercus rubra",count:805},
    {city:"Louisville",tree_name:"Platanus occidentalis",count:802},
    {city:"Louisville",tree_name:"Fraxinus americana",count:773},
    {city:"Lutz",tree_name:"Quercus virginiana",count:1},
    {city:"Madison",tree_name:"Acer platanoides",count:20912},
    {city:"Madison",tree_name:"Fraxinus pennsylvanica",count:17375},
    {city:"Madison",tree_name:"Tilia",count:4965},
    {city:"Madison",tree_name:"Tilia cordata",count:3893},
    {city:"Madison",tree_name:"Gleditsia triacanthos",count:3367},
    {city:"Madison",tree_name:"Fraxinus americana",count:2977},
    {city:"Madison",tree_name:"Tilia americana",count:2931},
    {city:"Madison",tree_name:"Celtis occidentalis",count:2658},
    {city:"Madison",tree_name:"Malus",count:2600},
    {city:"Madison",tree_name:"Acer freemanii",count:2235},
    {city:"Marietta",tree_name:"Juniperus virginiana",count:17},
    {city:"Marietta",tree_name:"Acer freemanii",count:14},
    {city:"Marietta",tree_name:"Magnolia virginiana",count:13},
    {city:"Marietta",tree_name:"Nyssa sylvatica",count:10},
    {city:"Marietta",tree_name:"Quercus virginiana",count:7},
    {city:"Marietta",tree_name:"Taxodium distichum",count:7},
    {city:"Marietta",tree_name:"Ginkgo biloba",count:6},
    {city:"Marietta",tree_name:"Cercis canadensis",count:3},
    {city:"Marietta",tree_name:"Lagerstroemia",count:3},
    {city:"Marietta",tree_name:"Magnolia",count:1},
    {city:"Miami",tree_name:"Pinus elliottii",count:45},
    {city:"Miami",tree_name:"Sabal palmetto",count:40},
    {city:"Miami",tree_name:"Adonidia merrillii",count:33},
    {city:"Miami",tree_name:"Pseudopanax crassifolius",count:31},
    {city:"Miami",tree_name:"Eugenia",count:30},
    {city:"Miami",tree_name:"Musa acuminata",count:30},
    {city:"Miami",tree_name:"Cocos nucifera",count:24},
    {city:"Miami",tree_name:"Mangifera indica",count:23},
    {city:"Miami",tree_name:"Coccoloba diversifolia",count:21},
    {city:"Miami",tree_name:"Ravenala madagascariensis",count:21},
    {city:"Milo",tree_name:"Fraxinus",count:81},
    {city:"Milo",tree_name:"Malus",count:48},
    {city:"Milo",tree_name:"Acer saccharinum",count:32},
    {city:"Milo",tree_name:"Acer ginnala",count:19},
    {city:"Milo",tree_name:"Acer saccharum",count:19},
    {city:"Milo",tree_name:"Acer platanoides",count:18},
    {city:"Milo",tree_name:"Betula nigra",count:14},
    {city:"Milo",tree_name:"Ulmus pumila",count:14},
    {city:"Milo",tree_name:"Quercus ellipsoidalis",count:12},
    {city:"Milo",tree_name:"Quercus macrocarpa",count:10},
    {city:"Milwaukee",tree_name:"Gleditsia triacanthos",count:1411},
    {city:"Milwaukee",tree_name:"Fraxinus pennsylvanica",count:1356},
    {city:"Milwaukee",tree_name:"Acer platanoides",count:912},
    {city:"Milwaukee",tree_name:"Acer saccharum",count:840},
    {city:"Milwaukee",tree_name:"Celtis occidentalis",count:700},
    {city:"Milwaukee",tree_name:"Quercus rubra",count:635},
    {city:"Milwaukee",tree_name:"Crataegus",count:584},
    {city:"Milwaukee",tree_name:"Fraxinus americana",count:454},
    {city:"Milwaukee",tree_name:"Tilia americana",count:424},
    {city:"Milwaukee",tree_name:"Malus tschonoskii",count:396},
    {city:"Minneapolis",tree_name:"Fraxinus pennsylvanica",count:28205},
    {city:"Minneapolis",tree_name:"Acer platanoides",count:20191},
    {city:"Minneapolis",tree_name:"Ulmus americana",count:16232},
    {city:"Minneapolis",tree_name:"Acer saccharum",count:15362},
    {city:"Minneapolis",tree_name:"Tilia americana",count:12745},
    {city:"Minneapolis",tree_name:"Celtis occidentalis",count:12736},
    {city:"Minneapolis",tree_name:"Tilia cordata",count:12687},
    {city:"Minneapolis",tree_name:"Gleditsia triacanthos",count:12676},
    {city:"Minneapolis",tree_name:"Unassigned",count:12042},
    {city:"Minneapolis",tree_name:"Acer rubrum",count:4196},
    {city:"Mitchellville",tree_name:"Acer saccharinum",count:51},
    {city:"Mitchellville",tree_name:"Fraxinus pennsylvanica",count:26},
    {city:"Mitchellville",tree_name:"Celtis occidentalis",count:22},
    {city:"Mitchellville",tree_name:"Acer platanoides",count:20},
    {city:"Mitchellville",tree_name:"Acer saccharum",count:18},
    {city:"Mitchellville",tree_name:"Acer rubrum",count:12},
    {city:"Mitchellville",tree_name:"Juglans nigra",count:10},
    {city:"Mitchellville",tree_name:"Malus",count:8},
    {city:"Mitchellville",tree_name:"Fraxinus",count:6},
    {city:"Mitchellville",tree_name:"Quercus rubra",count:6},
    {city:"Monroe",tree_name:"Acer saccharinum",count:33},
    {city:"Monroe",tree_name:"Acer saccharum",count:28},
    {city:"Monroe",tree_name:"Cercis canadensis",count:27},
    {city:"Monroe",tree_name:"Celtis occidentalis",count:25},
    {city:"Monroe",tree_name:"Acer",count:23},
    {city:"Monroe",tree_name:"Acer rubrum",count:23},
    {city:"Monroe",tree_name:"Picea pungens",count:20},
    {city:"Monroe",tree_name:"Malus",count:18},
    {city:"Monroe",tree_name:"Fraxinus pennsylvanica",count:17},
    {city:"Monroe",tree_name:"Quercus rubra",count:17},
    {city:"Muskego",tree_name:"Acer ginnala",count:1},
    {city:"Muskego",tree_name:"Fagus grandifolia",count:1},
    {city:"Nashville",tree_name:"Zelkova serrata",count:27},
    {city:"Nashville",tree_name:"Platanus acerifolia",count:25},
    {city:"Nashville",tree_name:"Acer rubrum",count:22},
    {city:"Nashville",tree_name:"Pyrus calleryana",count:19},
    {city:"Nashville",tree_name:"Quercus phellos",count:19},
    {city:"Nashville",tree_name:"Ulmus pumila",count:16},
    {city:"Nashville",tree_name:"Quercus shumardii",count:14},
    {city:"Nashville",tree_name:"Ulmus parvifolia",count:12},
    {city:"Nashville",tree_name:"Ginkgo biloba",count:10},
    {city:"Nashville",tree_name:"Liquidambar styraciflua",count:9},
    {city:"New Berlin",tree_name:"Fraxinus pennsylvanica",count:638},
    {city:"New Berlin",tree_name:"Picea pungens",count:612},
    {city:"New Berlin",tree_name:"Acer platanoides",count:476},
    {city:"New Berlin",tree_name:"Fraxinus americana",count:300},
    {city:"New Berlin",tree_name:"Gleditsia triacanthos",count:285},
    {city:"New Berlin",tree_name:"Malus tschonoskii",count:268},
    {city:"New Berlin",tree_name:"Tilia americana",count:238},
    {city:"New Berlin",tree_name:"Ulmus",count:181},
    {city:"New Berlin",tree_name:"Quercus alba",count:170},
    {city:"New Berlin",tree_name:"Carya ovata",count:159},
    {city:"New Orleans",tree_name:"Ilex attenuata",count:5},
    {city:"New Orleans",tree_name:"Ilex",count:3},
    {city:"New Orleans",tree_name:"Pyrus calleryana",count:3},
    {city:"New Orleans",tree_name:"Acer freemanii",count:2},
    {city:"New Orleans",tree_name:"Acer saccharum",count:2},
    {city:"New Orleans",tree_name:"Bauhinia variegata",count:2},
    {city:"New Orleans",tree_name:"Cercis canadensis",count:2},
    {city:"New Orleans",tree_name:"Crataegus crus-galli",count:2},
    {city:"New Orleans",tree_name:"Gleditsia triacanthos",count:2},
    {city:"New Orleans",tree_name:"Ilex vomitoria",count:2},
    {city:"New York",tree_name:"Platanus acerifolia",count:87014},
    {city:"New York",tree_name:"Gleditsia triacanthos",count:64264},
    {city:"New York",tree_name:"Pyrus calleryana",count:58931},
    {city:"New York",tree_name:"Quercus palustris",count:53185},
    {city:"New York",tree_name:"Acer platanoides",count:40112},
    {city:"New York",tree_name:"Tilia cordata",count:29742},
    {city:"New York",tree_name:"Prunus",count:29279},
    {city:"New York",tree_name:"Zelkova serrata",count:29258},
    {city:"New York",tree_name:"Ginkgo biloba",count:21024},
    {city:"New York",tree_name:"Styphnolobium japonicum",count:19338},
    {city:"Newton",tree_name:"Quercus macrocarpa",count:426},
    {city:"Newton",tree_name:"Fraxinus pennsylvanica",count:205},
    {city:"Newton",tree_name:"Pinus strobus",count:198},
    {city:"Newton",tree_name:"Quercus rubra",count:160},
    {city:"Newton",tree_name:"Malus",count:151},
    {city:"Newton",tree_name:"Carya",count:144},
    {city:"Newton",tree_name:"Acer",count:142},
    {city:"Newton",tree_name:"Juniperus virginiana",count:142},
    {city:"Newton",tree_name:"Celtis occidentalis",count:109},
    {city:"Newton",tree_name:"Quercus palustris",count:102},
    {city:"Oak Creek",tree_name:"Quercus rubra",count:37},
    {city:"Oak Creek",tree_name:"Malus tschonoskii",count:25},
    {city:"Oak Creek",tree_name:"Gleditsia triacanthos",count:13},
    {city:"Oak Creek",tree_name:"Acer saccharum",count:9},
    {city:"Oak Creek",tree_name:"Quercus alba",count:9},
    {city:"Oak Creek",tree_name:"Celtis occidentalis",count:8},
    {city:"Oak Creek",tree_name:"Pinus resinosa",count:8},
    {city:"Oak Creek",tree_name:"Syringa reticulata",count:8},
    {city:"Oak Creek",tree_name:"Acer platanoides",count:7},
    {city:"Oak Creek",tree_name:"Fraxinus pennsylvanica",count:7},
    {city:"Oakland",tree_name:"Liquidambar styraciflua",count:2397},
    {city:"Oakland",tree_name:"Prunus L.",count:2100},
    {city:"Oakland",tree_name:"Platanus acerifolia",count:1940},
    {city:"Oakland",tree_name:"Pyrus calleryana",count:1802},
    {city:"Oakland",tree_name:"Fraxinus",count:1629},
    {city:"Oakland",tree_name:"Lagerstroemia indica",count:1312},
    {city:"Oakland",tree_name:"Pyrus kawakamii",count:1049},
    {city:"Oakland",tree_name:"Magnolia grandiflora",count:978},
    {city:"Oakland",tree_name:"Pistacia chinensis",count:884},
    {city:"Oakland",tree_name:"Acer L.",count:706},
    {city:"Oakland Acres",tree_name:"Pinus strobus",count:10},
    {city:"Oakland Acres",tree_name:"Quercus rubra",count:6},
    {city:"Oakland Acres",tree_name:"Quercus palustris",count:5},
    {city:"Oakland Acres",tree_name:"Fraxinus pennsylvanica",count:4},
    {city:"Oakland Acres",tree_name:"Acer rubrum",count:3},
    {city:"Oakland Acres",tree_name:"Acer saccharinum",count:1},
    {city:"Oakland Acres",tree_name:"Fraxinus americana",count:1},
    {city:"Oakland Acres",tree_name:"Gleditsia triacanthos",count:1},
    {city:"Oakland Acres",tree_name:"Populus deltoides",count:1},
    {city:"Oklahoma City",tree_name:"Juniperus virginiana",count:711},
    {city:"Oklahoma City",tree_name:"Lagerstroemia indica",count:689},
    {city:"Oklahoma City",tree_name:"Quercus stellata",count:584},
    {city:"Oklahoma City",tree_name:"Pistacia chinensis",count:567},
    {city:"Oklahoma City",tree_name:"Ulmus parvifolia",count:455},
    {city:"Oklahoma City",tree_name:"Pinus nigra",count:453},
    {city:"Oklahoma City",tree_name:"Quercus shumardii",count:382},
    {city:"Oklahoma City",tree_name:"Taxodium distichum",count:376},
    {city:"Oklahoma City",tree_name:"Ulmus pumila",count:326},
    {city:"Oklahoma City",tree_name:"Quercus marilandica",count:323},
    {city:"Ontario",tree_name:"Lagerstroemia indica",count:4630},
    {city:"Ontario",tree_name:"Liquidambar styraciflua",count:4392},
    {city:"Ontario",tree_name:"Cinnamomum camphora",count:3900},
    {city:"Ontario",tree_name:"Platanus acerifolia",count:3328},
    {city:"Ontario",tree_name:"Pinus canariensis",count:3307},
    {city:"Ontario",tree_name:"Pyrus calleryana",count:2793},
    {city:"Ontario",tree_name:"Syagrus romanzoffiana",count:2109},
    {city:"Ontario",tree_name:"Washingtonia robusta",count:1584},
    {city:"Ontario",tree_name:"Pistacia chinensis",count:1343},
    {city:"Ontario",tree_name:"Schinus molle",count:1224},
    {city:"Orlando",tree_name:"Acer rubrum",count:6},
    {city:"Orlando",tree_name:"Carya illinoinensis",count:6},
    {city:"Orlando",tree_name:"Cinnamomum camphora",count:6},
    {city:"Orlando",tree_name:"Lagerstroemia indica",count:6},
    {city:"Orlando",tree_name:"Liquidambar orientalis",count:6},
    {city:"Orlando",tree_name:"Liquidambar styraciflua",count:6},
    {city:"Orlando",tree_name:"Magnolia grandiflora",count:6},
    {city:"Orlando",tree_name:"Melaleuca quinquenervia",count:6},
    {city:"Orlando",tree_name:"Melia azedarach",count:6},
    {city:"Orlando",tree_name:"Phoenix canariensis",count:6},
    {city:"Overland Park",tree_name:"Acer rubrum",count:13289},
    {city:"Overland Park",tree_name:"Fraxinus americana",count:7654},
    {city:"Overland Park",tree_name:"Quercus palustris",count:3419},
    {city:"Overland Park",tree_name:"Liquidambar styraciflua",count:1983},
    {city:"Overland Park",tree_name:"Fraxinus pennsylvanica",count:1929},
    {city:"Overland Park",tree_name:"Malus",count:1418},
    {city:"Overland Park",tree_name:"Pyrus calleryana",count:1357},
    {city:"Overland Park",tree_name:"Acer saccharinum",count:1213},
    {city:"Overland Park",tree_name:"Gleditsia triacanthos",count:964},
    {city:"Overland Park",tree_name:"Tilia cordata",count:900},
    {city:"Panora",tree_name:"Acer saccharum",count:56},
    {city:"Panora",tree_name:"Fraxinus pennsylvanica",count:45},
    {city:"Panora",tree_name:"Acer saccharinum",count:22},
    {city:"Panora",tree_name:"Acer platanoides",count:21},
    {city:"Panora",tree_name:"Malus",count:16},
    {city:"Panora",tree_name:"Acer rubrum",count:14},
    {city:"Panora",tree_name:"Juglans nigra",count:6},
    {city:"Panora",tree_name:"Platanus occidentalis",count:6},
    {city:"Panora",tree_name:"Tilia americana",count:5},
    {city:"Panora",tree_name:"Fraxinus americana",count:4},
    {city:"Phoenix",tree_name:"Fraxinus velutina",count:19},
    {city:"Phoenix",tree_name:"Syagrus romanzoffiana",count:16},
    {city:"Phoenix",tree_name:"Cercidium floridum",count:14},
    {city:"Phoenix",tree_name:"Fraxinus",count:12},
    {city:"Phoenix",tree_name:"Citrus paradisi",count:11},
    {city:"Phoenix",tree_name:"Morus alba",count:10},
    {city:"Phoenix",tree_name:"Pinus halepensis",count:9},
    {city:"Phoenix",tree_name:"Ficus microcarpa",count:8},
    {city:"Phoenix",tree_name:"Citrus aurantium",count:7},
    {city:"Phoenix",tree_name:"Citrus sinensis",count:6},
    {city:"Pittsburgh",tree_name:"Acer platanoides",count:3715},
    {city:"Pittsburgh",tree_name:"Acer rubrum",count:3422},
    {city:"Pittsburgh",tree_name:"Platanus acerifolia",count:3238},
    {city:"Pittsburgh",tree_name:"Pyrus calleryana",count:2969},
    {city:"Pittsburgh",tree_name:"Tilia cordata",count:2413},
    {city:"Pittsburgh",tree_name:"Gleditsia triacanthos",count:2120},
    {city:"Pittsburgh",tree_name:"Quercus palustris",count:1672},
    {city:"Pittsburgh",tree_name:"Malus",count:1311},
    {city:"Pittsburgh",tree_name:"Ginkgo biloba",count:1218},
    {city:"Pittsburgh",tree_name:"Quercus rubra",count:978},
    {city:"Plano",tree_name:"Ulmus crassifolia",count:3641},
    {city:"Plano",tree_name:"Celtis occidentalis",count:3279},
    {city:"Plano",tree_name:"Quercus rubra",count:2598},
    {city:"Plano",tree_name:"Quercus virginiana",count:1906},
    {city:"Plano",tree_name:"Taxodium distichum",count:1598},
    {city:"Plano",tree_name:"Carya illinoinensis",count:1246},
    {city:"Plano",tree_name:"Fraxinus",count:1208},
    {city:"Plano",tree_name:"Pistacia chinensis",count:822},
    {city:"Plano",tree_name:"Pyrus calleryana",count:815},
    {city:"Plano",tree_name:"Ulmus americana",count:660},
    {city:"Pleasant Hill",tree_name:"Malus",count:200},
    {city:"Pleasant Hill",tree_name:"Celtis occidentalis",count:168},
    {city:"Pleasant Hill",tree_name:"Quercus rubra",count:91},
    {city:"Pleasant Hill",tree_name:"Quercus macrocarpa",count:90},
    {city:"Pleasant Hill",tree_name:"Pinus strobus",count:80},
    {city:"Pleasant Hill",tree_name:"Carya",count:48},
    {city:"Pleasant Hill",tree_name:"Tilia americana",count:45},
    {city:"Pleasant Hill",tree_name:"Fraxinus pennsylvanica",count:44},
    {city:"Pleasant Hill",tree_name:"Catalpa",count:37},
    {city:"Pleasant Hill",tree_name:"Quercus bicolor",count:37},
    {city:"Polk City",tree_name:"Malus",count:55},
    {city:"Polk City",tree_name:"Pyrus",count:21},
    {city:"Polk City",tree_name:"Fraxinus pennsylvanica",count:12},
    {city:"Polk City",tree_name:"Acer rubrum",count:9},
    {city:"Polk City",tree_name:"Quercus bicolor",count:6},
    {city:"Polk City",tree_name:"Acer platanoides",count:4},
    {city:"Polk City",tree_name:"Acer saccharum",count:3},
    {city:"Polk City",tree_name:"Fraxinus americana",count:3},
    {city:"Polk City",tree_name:"Quercus macrocarpa",count:2},
    {city:"Polk City",tree_name:"Juglans nigra",count:1},
    {city:"Portland",tree_name:"Prunus",count:25597},
    {city:"Portland",tree_name:"Acer platanoides",count:19179},
    {city:"Portland",tree_name:"Acer rubrum",count:15464},
    {city:"Portland",tree_name:"Pyrus",count:11678},
    {city:"Portland",tree_name:"Acer",count:10615},
    {city:"Portland",tree_name:"Fraxinus",count:9272},
    {city:"Portland",tree_name:"Cornus",count:8641},
    {city:"Portland",tree_name:"Quercus",count:7273},
    {city:"Portland",tree_name:"Malus",count:6755},
    {city:"Portland",tree_name:"Betula",count:6325},
    {city:"Prairie City",tree_name:"Picea",count:55},
    {city:"Prairie City",tree_name:"Acer saccharinum",count:33},
    {city:"Prairie City",tree_name:"Thuja occidentalis",count:29},
    {city:"Prairie City",tree_name:"Acer saccharum",count:26},
    {city:"Prairie City",tree_name:"Fraxinus",count:18},
    {city:"Prairie City",tree_name:"Acer platanoides",count:16},
    {city:"Prairie City",tree_name:"Celtis occidentalis",count:15},
    {city:"Prairie City",tree_name:"Acer rubrum",count:14},
    {city:"Prairie City",tree_name:"Malus",count:11},
    {city:"Prairie City",tree_name:"Pyrus",count:10},
    {city:"Providence",tree_name:"Acer platanoides",count:2940},
    {city:"Providence",tree_name:"Pyrus calleryana",count:2420},
    {city:"Providence",tree_name:"Gleditsia triacanthos",count:1844},
    {city:"Providence",tree_name:"Platanus acerifolia",count:1596},
    {city:"Providence",tree_name:"Fraxinus pennsylvanica",count:1547},
    {city:"Providence",tree_name:"Acer rubrum",count:1255},
    {city:"Providence",tree_name:"Zelkova serrata",count:1055},
    {city:"Providence",tree_name:"Tilia cordata",count:843},
    {city:"Providence",tree_name:"Quercus palustris",count:609},
    {city:"Providence",tree_name:"Prunus",count:523},
    {city:"Rancho Cucamonga",tree_name:"Lagerstroemia indica",count:12889},
    {city:"Rancho Cucamonga",tree_name:"Platanus acerifolia",count:5698},
    {city:"Rancho Cucamonga",tree_name:"Eucalyptus globulus",count:5549},
    {city:"Rancho Cucamonga",tree_name:"Magnolia grandiflora",count:5016},
    {city:"Rancho Cucamonga",tree_name:"Pyrus calleryana",count:4941},
    {city:"Rancho Cucamonga",tree_name:"Liquidambar styraciflua",count:3727},
    {city:"Rancho Cucamonga",tree_name:"Pinus",count:3702},
    {city:"Rancho Cucamonga",tree_name:"Brachychiton populneus",count:3658},
    {city:"Rancho Cucamonga",tree_name:"Pistacia chinensis",count:3213},
    {city:"Rancho Cucamonga",tree_name:"Pinus canariensis",count:2355},
    {city:"Redfield",tree_name:"Malus",count:20},
    {city:"Redfield",tree_name:"Acer saccharinum",count:17},
    {city:"Redfield",tree_name:"Fraxinus pennsylvanica",count:15},
    {city:"Redfield",tree_name:"Acer",count:13},
    {city:"Redfield",tree_name:"Celtis occidentalis",count:10},
    {city:"Redfield",tree_name:"Ulmus pumila",count:9},
    {city:"Redfield",tree_name:"Acer nigrum",count:8},
    {city:"Redfield",tree_name:"Gleditsia triacanthos",count:7},
    {city:"Redfield",tree_name:"Quercus bicolor",count:7},
    {city:"Redfield",tree_name:"Acer rubrum",count:6},
    {city:"Richmond",tree_name:"Acer saccharum",count:227},
    {city:"Richmond",tree_name:"Quercus phellos",count:171},
    {city:"Richmond",tree_name:"Lagerstroemia indica",count:161},
    {city:"Richmond",tree_name:"Acer rubrum",count:148},
    {city:"Richmond",tree_name:"Quercus palustris",count:133},
    {city:"Richmond",tree_name:"Zelkova serrata",count:129},
    {city:"Richmond",tree_name:"Ulmus alata",count:79},
    {city:"Richmond",tree_name:"Fraxinus pennsylvanica",count:53},
    {city:"Richmond",tree_name:"Pyrus calleryana",count:46},
    {city:"Richmond",tree_name:"Acer campestre",count:45},
    {city:"Rochester",tree_name:"Gleditsia triacanthos",count:6301},
    {city:"Rochester",tree_name:"Tilia cordata",count:3329},
    {city:"Rochester",tree_name:"Platanus acerifolia",count:2968},
    {city:"Rochester",tree_name:"Fraxinus pennsylvanica",count:2497},
    {city:"Rochester",tree_name:"Quercus rubra",count:2177},
    {city:"Rochester",tree_name:"Acer rubrum",count:1994},
    {city:"Rochester",tree_name:"Zelkova serrata",count:1581},
    {city:"Rochester",tree_name:"Acer saccharum",count:1541},
    {city:"Rochester",tree_name:"Acer campestre",count:1495},
    {city:"Rochester",tree_name:"Acer saccharinum",count:1012},
    {city:"Runnells",tree_name:"Fraxinus pennsylvanica",count:12},
    {city:"Runnells",tree_name:"Acer saccharinum",count:11},
    {city:"Runnells",tree_name:"Acer",count:6},
    {city:"Runnells",tree_name:"Acer rubrum",count:6},
    {city:"Runnells",tree_name:"Picea",count:6},
    {city:"Runnells",tree_name:"Malus",count:3},
    {city:"Runnells",tree_name:"Quercus bicolor",count:3},
    {city:"Runnells",tree_name:"Acer platanoides",count:2},
    {city:"Runnells",tree_name:"Quercus palustris",count:2},
    {city:"Runnells",tree_name:"Thuja occidentalis",count:2},
    {city:"Sacramento",tree_name:"Platanus acerifolia",count:14111},
    {city:"Sacramento",tree_name:"Pistacia chinensis",count:4580},
    {city:"Sacramento",tree_name:"Pyrus calleryana",count:4285},
    {city:"Sacramento",tree_name:"Lagerstroemia indica",count:4146},
    {city:"Sacramento",tree_name:"Ulmus parvifolia",count:4047},
    {city:"Sacramento",tree_name:"Zelkova serrata",count:3861},
    {city:"Sacramento",tree_name:"Quercus lobata",count:3693},
    {city:"Sacramento",tree_name:"Sequoia sempervirens",count:2909},
    {city:"Sacramento",tree_name:"Fraxinus velutina",count:2842},
    {city:"Sacramento",tree_name:"Liquidambar styraciflua",count:1933},
    {city:"San Diego",tree_name:"Syagrus romanzoffianum",count:22624},
    {city:"San Diego",tree_name:"Washingtonia robusta",count:15129},
    {city:"San Diego",tree_name:"Cupaniopsis anacardioides",count:13608},
    {city:"San Diego",tree_name:"Eucalyptus",count:13269},
    {city:"San Diego",tree_name:"Pinus",count:12677},
    {city:"San Diego",tree_name:"Liquidambar styraciflua",count:10323},
    {city:"San Diego",tree_name:"Jacaranda acutifolia",count:9831},
    {city:"San Diego",tree_name:"Lophostemon confertus",count:7591},
    {city:"San Diego",tree_name:"Platanus racemosa",count:7330},
    {city:"San Diego",tree_name:"Podocarpus gracilior",count:6161},
    {city:"San Francisco",tree_name:"Platanus acerifolia",count:11925},
    {city:"San Francisco",tree_name:"Metrosideros excelsa",count:8681},
    {city:"San Francisco",tree_name:"Tristaniopsis laurina",count:8509},
    {city:"San Francisco",tree_name:"Lophostemon confertus",count:8236},
    {city:"San Francisco",tree_name:"Magnolia grandiflora",count:7793},
    {city:"San Francisco",tree_name:"Prunus cerasifera",count:7113},
    {city:"San Francisco",tree_name:"Pittosporum undulatum",count:6922},
    {city:"San Francisco",tree_name:"Prunus serrulata",count:6756},
    {city:"San Francisco",tree_name:"Ficus microcarpa",count:6650},
    {city:"San Francisco",tree_name:"Arbutus",count:5568},
    {city:"San Jose",tree_name:"Platanus acerifolia",count:26291},
    {city:"San Jose",tree_name:"Pistacia chinensis",count:24316},
    {city:"San Jose",tree_name:"Lagerstroemia indica",count:21636},
    {city:"San Jose",tree_name:"Liquidambar styraciflua",count:14644},
    {city:"San Jose",tree_name:"Pyrus calleryana",count:9631},
    {city:"San Jose",tree_name:"Zelkova serrata",count:7669},
    {city:"San Jose",tree_name:"Cupressus sempervirens",count:7208},
    {city:"San Jose",tree_name:"Magnolia grandiflora",count:7080},
    {city:"San Jose",tree_name:"Prunus cerasifera",count:6999},
    {city:"San Jose",tree_name:"Fraxinus angustifolia",count:5626},
    {city:"SandySprings",tree_name:"Quercus falcata",count:26},
    {city:"SandySprings",tree_name:"Cornus florida",count:14},
    {city:"SandySprings",tree_name:"Pinus taeda",count:12},
    {city:"SandySprings",tree_name:"Rhus copallina",count:12},
    {city:"SandySprings",tree_name:"Cercis canadensis",count:11},
    {city:"SandySprings",tree_name:"Asimina triloba",count:10},
    {city:"SandySprings",tree_name:"Carya glabra",count:10},
    {city:"SandySprings",tree_name:"Ilex opaca",count:10},
    {city:"SandySprings",tree_name:"Prunus",count:10},
    {city:"SandySprings",tree_name:"Betula nigra",count:9},
    {city:"Santa Rosa",tree_name:"Quercus",count:468},
    {city:"Santa Rosa",tree_name:"Sequoia sempervirens",count:203},
    {city:"Santa Rosa",tree_name:"Abies",count:155},
    {city:"Santa Rosa",tree_name:"Acer",count:139},
    {city:"Santa Rosa",tree_name:"Platanus acerifolia",count:87},
    {city:"Santa Rosa",tree_name:"Pyrus",count:68},
    {city:"Santa Rosa",tree_name:"Pinus",count:24},
    {city:"Santa Rosa",tree_name:"Prunus",count:22},
    {city:"Santa Rosa",tree_name:"Celtis occidentalis",count:17},
    {city:"Santa Rosa",tree_name:"Cedrus",count:9},
    {city:"Scottdale",tree_name:"Quercus nuttallii",count:21},
    {city:"Scottdale",tree_name:"Acer rubrum",count:11},
    {city:"Scottdale",tree_name:"Taxodium distichum",count:6},
    {city:"Scottdale",tree_name:"Quercus alba",count:4},
    {city:"Scottdale",tree_name:"Crataegus viridis",count:3},
    {city:"Seattle",tree_name:"Prunus cerasifera",count:8241},
    {city:"Seattle",tree_name:"Acer rubrum",count:7537},
    {city:"Seattle",tree_name:"Acer platanoides",count:6301},
    {city:"Seattle",tree_name:"Malus",count:5201},
    {city:"Seattle",tree_name:"Prunus L.",count:4938},
    {city:"Seattle",tree_name:"Acer palmatum",count:4564},
    {city:"Seattle",tree_name:"Pyrus calleryana",count:4459},
    {city:"Seattle",tree_name:"Prunus",count:3935},
    {city:"Seattle",tree_name:"Acer truncatum",count:3745},
    {city:"Seattle",tree_name:"Crataegus laevigata",count:3645},
    {city:"Seffner",tree_name:"Quercus laurifolia",count:4},
    {city:"Seffner",tree_name:"Quercus nigra",count:4},
    {city:"Seffner",tree_name:"Quercus virginiana",count:3},
    {city:"Seffner",tree_name:"Ulmus parvifolia",count:1},
    {city:"Shorewood",tree_name:"Crataegus",count:16},
    {city:"Shorewood",tree_name:"Juglans nigra",count:14},
    {city:"Shorewood",tree_name:"Malus tschonoskii",count:11},
    {city:"Shorewood",tree_name:"Acer platanoides",count:9},
    {city:"Shorewood",tree_name:"Acer saccharum",count:8},
    {city:"Shorewood",tree_name:"Gymnocladus dioicus",count:7},
    {city:"Shorewood",tree_name:"Fraxinus americana",count:3},
    {city:"Shorewood",tree_name:"Fraxinus pennsylvanica",count:3},
    {city:"Shorewood",tree_name:"Quercus alba",count:3},
    {city:"Shorewood",tree_name:"Quercus rubra",count:3},
    {city:"Sioux Falls",tree_name:"Fraxinus pennsylvanica",count:21452},
    {city:"Sioux Falls",tree_name:"Acer platanoides",count:5704},
    {city:"Sioux Falls",tree_name:"Acer freemanii",count:4933},
    {city:"Sioux Falls",tree_name:"Acer saccharinum",count:4327},
    {city:"Sioux Falls",tree_name:"Tilia cordata",count:3095},
    {city:"Sioux Falls",tree_name:"Gleditsia triacanthos",count:2331},
    {city:"Sioux Falls",tree_name:"Celtis occidentalis",count:1599},
    {city:"Sioux Falls",tree_name:"Picea pungens",count:1290},
    {city:"Sioux Falls",tree_name:"Acer saccharum",count:1274},
    {city:"Sioux Falls",tree_name:"Malus",count:1085},
    {city:"South Milwaukee",tree_name:"Acer saccharum",count:54},
    {city:"South Milwaukee",tree_name:"Fraxinus americana",count:45},
    {city:"South Milwaukee",tree_name:"Celtis occidentalis",count:31},
    {city:"South Milwaukee",tree_name:"Gleditsia triacanthos",count:28},
    {city:"South Milwaukee",tree_name:"Quercus rubra",count:28},
    {city:"South Milwaukee",tree_name:"Picea",count:23},
    {city:"South Milwaukee",tree_name:"Ulmus",count:22},
    {city:"South Milwaukee",tree_name:"Acer platanoides",count:19},
    {city:"South Milwaukee",tree_name:"Fraxinus pennsylvanica",count:19},
    {city:"South Milwaukee",tree_name:"Malus tschonoskii",count:19},
    {city:"St. Louis",tree_name:"Acer rubrum",count:8575},
    {city:"St. Louis",tree_name:"Fraxinus pennsylvanica",count:7761},
    {city:"St. Louis",tree_name:"Pyrus calleryana",count:7210},
    {city:"St. Louis",tree_name:"Quercus palustris",count:6497},
    {city:"St. Louis",tree_name:"Fraxinus americana",count:4557},
    {city:"St. Louis",tree_name:"Acer saccharum",count:4172},
    {city:"St. Louis",tree_name:"Tilia cordata",count:3682},
    {city:"St. Louis",tree_name:"Acer saccharinum",count:3115},
    {city:"St. Louis",tree_name:"Gleditsia triacanthos",count:3013},
    {city:"St. Louis",tree_name:"Cercis canadensis",count:2886},
    {city:"Stockton",tree_name:"Pistacia chinensis",count:11392},
    {city:"Stockton",tree_name:"Platanus acerifolia",count:7552},
    {city:"Stockton",tree_name:"Lagerstroemia indica",count:7354},
    {city:"Stockton",tree_name:"Celtis sinensis",count:7179},
    {city:"Stockton",tree_name:"Pyrus calleryana",count:5296},
    {city:"Stockton",tree_name:"Fraxinus velutina",count:4879},
    {city:"Stockton",tree_name:"Liquidambar styraciflua",count:4110},
    {city:"Stockton",tree_name:"Magnolia grandiflora",count:3762},
    {city:"Stockton",tree_name:"Zelkova serrata",count:3379},
    {city:"Stockton",tree_name:"Sequoia sempervirens",count:2936},
    {city:"Stuart",tree_name:"Acer saccharum",count:94},
    {city:"Stuart",tree_name:"Fraxinus pennsylvanica",count:94},
    {city:"Stuart",tree_name:"Acer saccharinum",count:58},
    {city:"Stuart",tree_name:"Acer platanoides",count:50},
    {city:"Stuart",tree_name:"Gleditsia triacanthos",count:18},
    {city:"Stuart",tree_name:"Quercus palustris",count:18},
    {city:"Stuart",tree_name:"Acer rubrum",count:13},
    {city:"Stuart",tree_name:"Juglans nigra",count:11},
    {city:"Stuart",tree_name:"Tilia americana",count:10},
    {city:"Stuart",tree_name:"Malus",count:8},
    {city:"Sully",tree_name:"Acer saccharum",count:22},
    {city:"Sully",tree_name:"Acer saccharinum",count:21},
    {city:"Sully",tree_name:"Fraxinus pennsylvanica",count:20},
    {city:"Sully",tree_name:"Picea",count:15},
    {city:"Sully",tree_name:"Gleditsia triacanthos",count:11},
    {city:"Sully",tree_name:"Fraxinus americana",count:10},
    {city:"Sully",tree_name:"Acer platanoides",count:7},
    {city:"Sully",tree_name:"Tilia cordata",count:7},
    {city:"Sully",tree_name:"Acer rubrum",count:6},
    {city:"Sully",tree_name:"Quercus palustris",count:6},
    {city:"Tampa",tree_name:"Quercus virginiana",count:5379},
    {city:"Tampa",tree_name:"Quercus geminata",count:3248},
    {city:"Tampa",tree_name:"Lagerstroemia indica",count:2851},
    {city:"Tampa",tree_name:"Sabal palmetto",count:1381},
    {city:"Tampa",tree_name:"Pinus elliottii",count:1236},
    {city:"Tampa",tree_name:"Quercus laurifolia",count:1099},
    {city:"Tampa",tree_name:"Washingtonia robusta",count:1007},
    {city:"Tampa",tree_name:"Prunus caroliniana",count:855},
    {city:"Tampa",tree_name:"Callistemon viminalis",count:556},
    {city:"Tampa",tree_name:"Taxodium distichum",count:498},
    {city:"Temple Terrace",tree_name:"Quercus geminata",count:3},
    {city:"Temple Terrace",tree_name:"Quercus laevis",count:3},
    {city:"Temple Terrace",tree_name:"Platanus occidentalis",count:1},
    {city:"Temple Terrace",tree_name:"Quercus incana",count:1},
    {city:"Tucker",tree_name:"Quercus nuttallii",count:29},
    {city:"Tucker",tree_name:"Ulmus americana",count:18},
    {city:"Tucker",tree_name:"Quercus shumardii",count:8},
    {city:"Unincorporated",tree_name:"Quercus nuttallii",count:61},
    {city:"Unincorporated",tree_name:"Cercis canadensis",count:52},
    {city:"Unincorporated",tree_name:"Nyssa sylvatica",count:47},
    {city:"Unincorporated",tree_name:"Lagerstroemia indica",count:42},
    {city:"Unincorporated",tree_name:"Quercus lyrata",count:38},
    {city:"Unincorporated",tree_name:"Acer rubrum",count:33},
    {city:"Unincorporated",tree_name:"Quercus alba",count:30},
    {city:"Unincorporated",tree_name:"Acer buergerianum",count:29},
    {city:"Unincorporated",tree_name:"Magnolia virginiana",count:22},
    {city:"Unincorporated",tree_name:"Cornus florida",count:15},
    {city:"Union",tree_name:"Acer saccharum",count:47},
    {city:"Union",tree_name:"Acer nigrum",count:21},
    {city:"Union",tree_name:"Acer platanoides",count:19},
    {city:"Union",tree_name:"Acer saccharinum",count:15},
    {city:"Union",tree_name:"Fraxinus",count:13},
    {city:"Union",tree_name:"Juglans nigra",count:7},
    {city:"Union",tree_name:"Malus",count:7},
    {city:"Union",tree_name:"Picea",count:6},
    {city:"Union",tree_name:"Acer rubrum",count:4},
    {city:"Union",tree_name:"Celtis occidentalis",count:4},
    {city:"Van Meter",tree_name:"Acer saccharum",count:11},
    {city:"Van Meter",tree_name:"Platanus occidentalis",count:8},
    {city:"Van Meter",tree_name:"Acer saccharinum",count:6},
    {city:"Van Meter",tree_name:"Quercus palustris",count:6},
    {city:"Van Meter",tree_name:"Ulmus pumila",count:6},
    {city:"Van Meter",tree_name:"Acer platanoides",count:3},
    {city:"Van Meter",tree_name:"Fraxinus pennsylvanica",count:3},
    {city:"Van Meter",tree_name:"Malus",count:3},
    {city:"Van Meter",tree_name:"Acer",count:2},
    {city:"Van Meter",tree_name:"Gleditsia triacanthos",count:1},
    {city:"Waipahu",tree_name:"Cassia nealiae",count:27},
    {city:"Waipahu",tree_name:"Lagerstroemia speciosa",count:13},
    {city:"Waipahu",tree_name:"Cassia fistula",count:2},
    {city:"Waipahu",tree_name:"Harpullia pendula",count:1},
    {city:"Washington DC",tree_name:"Acer rubrum",count:12707},
    {city:"Washington DC",tree_name:"Quercus phellos",count:9976},
    {city:"Washington DC",tree_name:"Ulmus americana",count:9012},
    {city:"Washington DC",tree_name:"Quercus palustris",count:8897},
    {city:"Washington DC",tree_name:"Zelkova serrata",count:6343},
    {city:"Washington DC",tree_name:"Quercus rubra",count:5849},
    {city:"Washington DC",tree_name:"Platanus acerifolia",count:5742},
    {city:"Washington DC",tree_name:"Acer saccharum",count:5408},
    {city:"Washington DC",tree_name:"Ginkgo biloba",count:4731},
    {city:"Washington DC",tree_name:"Lagerstroemia indica",count:4324},
    {city:"Watertown",tree_name:"Acer platanoides",count:976},
    {city:"Watertown",tree_name:"Tilia cordata",count:401},
    {city:"Watertown",tree_name:"Pyrus calleryana",count:397},
    {city:"Watertown",tree_name:"Gleditsia triacanthos",count:385},
    {city:"Watertown",tree_name:"Malus tschonoskii",count:354},
    {city:"Watertown",tree_name:"Fraxinus americana",count:337},
    {city:"Watertown",tree_name:"Syringa reticulata",count:285},
    {city:"Watertown",tree_name:"Fraxinus pennsylvanica",count:259},
    {city:"Watertown",tree_name:"Acer saccharinum",count:244},
    {city:"Watertown",tree_name:"Acer freemanii",count:204},
    {city:"Waukee",tree_name:"Fraxinus pennsylvanica",count:218},
    {city:"Waukee",tree_name:"Malus",count:200},
    {city:"Waukee",tree_name:"Picea",count:199},
    {city:"Waukee",tree_name:"Tilia cordata",count:122},
    {city:"Waukee",tree_name:"Pinus strobus",count:111},
    {city:"Waukee",tree_name:"Morus",count:104},
    {city:"Waukee",tree_name:"Gleditsia triacanthos",count:103},
    {city:"Waukee",tree_name:"Acer",count:88},
    {city:"Waukee",tree_name:"Celtis occidentalis",count:85},
    {city:"Waukee",tree_name:"Fraxinus americana",count:72},
    {city:"Wauwatosa",tree_name:"Fraxinus pennsylvanica",count:265},
    {city:"Wauwatosa",tree_name:"Acer saccharum",count:186},
    {city:"Wauwatosa",tree_name:"Acer platanoides",count:171},
    {city:"Wauwatosa",tree_name:"Gleditsia triacanthos",count:157},
    {city:"Wauwatosa",tree_name:"Quercus rubra",count:151},
    {city:"Wauwatosa",tree_name:"Celtis occidentalis",count:100},
    {city:"Wauwatosa",tree_name:"Fraxinus americana",count:89},
    {city:"Wauwatosa",tree_name:"Crataegus",count:74},
    {city:"Wauwatosa",tree_name:"Malus tschonoskii",count:63},
    {city:"Wauwatosa",tree_name:"Tilia americana",count:44},
    {city:"West Allis",tree_name:"Celtis occidentalis",count:348},
    {city:"West Allis",tree_name:"Gleditsia triacanthos",count:238},
    {city:"West Allis",tree_name:"Fraxinus pennsylvanica",count:144},
    {city:"West Allis",tree_name:"Malus tschonoskii",count:87},
    {city:"West Allis",tree_name:"Acer saccharum",count:70},
    {city:"West Allis",tree_name:"Crataegus",count:68},
    {city:"West Allis",tree_name:"Juglans nigra",count:61},
    {city:"West Allis",tree_name:"Acer platanoides",count:43},
    {city:"West Allis",tree_name:"Tilia americana",count:42},
    {city:"West Allis",tree_name:"Quercus rubra",count:41},
    {city:"West Bend",tree_name:"Populus tremuloides",count:1},
    {city:"West Milwaukee",tree_name:"Acer saccharum",count:22},
    {city:"West Milwaukee",tree_name:"Crataegus",count:19},
    {city:"West Milwaukee",tree_name:"Gleditsia triacanthos",count:16},
    {city:"West Milwaukee",tree_name:"Juniperus virginiana",count:13},
    {city:"West Milwaukee",tree_name:"Quercus rubra",count:9},
    {city:"West Milwaukee",tree_name:"Juglans nigra",count:8},
    {city:"West Milwaukee",tree_name:"Acer platanoides",count:5},
    {city:"West Milwaukee",tree_name:"Celtis occidentalis",count:4},
    {city:"West Milwaukee",tree_name:"Fraxinus",count:4},
    {city:"West Milwaukee",tree_name:"Cercis canadensis",count:2},
    {city:"Whitefish Bay",tree_name:"Gleditsia triacanthos",count:10},
    {city:"Whitefish Bay",tree_name:"Robinia pseudoacacia",count:10},
    {city:"Whitefish Bay",tree_name:"Tilia",count:8},
    {city:"Whitefish Bay",tree_name:"Quercus rubra",count:7},
    {city:"Whitefish Bay",tree_name:"Fraxinus",count:5},
    {city:"Whitefish Bay",tree_name:"Fraxinus pennsylvanica",count:5},
    {city:"Whitefish Bay",tree_name:"Malus tschonoskii",count:4},
    {city:"Whitefish Bay",tree_name:"Tilia americana",count:4},
    {city:"Whitefish Bay",tree_name:"Fraxinus americana",count:3},
    {city:"Whitefish Bay",tree_name:"Acer platanoides",count:2},
    {city:"Wind Lake",tree_name:"Carya ovata",count:1},
    {city:"Windsor Heights",tree_name:"Fraxinus pennsylvanica",count:39},
    {city:"Windsor Heights",tree_name:"Pyrus",count:32},
    {city:"Windsor Heights",tree_name:"Populus",count:26},
    {city:"Windsor Heights",tree_name:"Malus",count:25},
    {city:"Windsor Heights",tree_name:"Gleditsia triacanthos",count:22},
    {city:"Windsor Heights",tree_name:"Acer saccharum",count:17},
    {city:"Windsor Heights",tree_name:"Pinus strobus",count:17},
    {city:"Windsor Heights",tree_name:"Syringa",count:17},
    {city:"Windsor Heights",tree_name:"Acer saccharinum",count:16},
    {city:"Windsor Heights",tree_name:"Cercis canadensis",count:14},
    {city:"Woodward",tree_name:"Acer saccharinum",count:105},
    {city:"Woodward",tree_name:"Acer platanoides",count:81},
    {city:"Woodward",tree_name:"Acer nigrum",count:66},
    {city:"Woodward",tree_name:"Fraxinus pennsylvanica",count:49},
    {city:"Woodward",tree_name:"Malus",count:26},
    {city:"Woodward",tree_name:"Juglans nigra",count:25},
    {city:"Woodward",tree_name:"Celtis occidentalis",count:24},
    {city:"Woodward",tree_name:"Gleditsia triacanthos",count:15},
    {city:"Woodward",tree_name:"Tilia cordata",count:12},
    {city:"Woodward",tree_name:"Picea abies",count:8},
    {city:"Worcester",tree_name:"Acer platanoides",count:6},
    {city:"Worcester",tree_name:"Acer pseudoplatanus",count:6},
    {city:"Worcester",tree_name:"Acer rubrum",count:6},
    {city:"Worcester",tree_name:"Acer saccharinum",count:6},
    {city:"Worcester",tree_name:"Acer saccharum",count:6},
    {city:"Worcester",tree_name:"Aesculus hippocastanum",count:6},
    {city:"Worcester",tree_name:"Ailanthus altissima",count:6},
    {city:"Worcester",tree_name:"Carya glabra",count:6},
    {city:"Worcester",tree_name:"Catalpa speciosa",count:6},
    {city:"Worcester",tree_name:"Fraxinus americana",count:6},
    // Add more data as needed
];


// Get the unique cities
const uniqueCities = [...new Set(data.map(d => d.city))];

// Populate the city dropdown
const cityDropdown = d3.select("#citySelection");
cityDropdown
    .selectAll("option")
    .data(uniqueCities)
    .enter()
    .append("option")
    .text(d => d);

// Create a function to draw the bar chart based on the selected city
function drawBarChart(selectedCity) {
    const filteredData = data.filter(d => d.city === selectedCity);

    const margin = { top: 20, right: 20, bottom: 60, left: 60 };
    const width = 800 - margin.left - margin.right;
    const height = 400 - margin.top - margin.bottom;

    d3.select("#chart").html("");

    const svg = d3
        .select("#chart")
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

    const x = d3.scaleBand().domain(filteredData.map(d => d.tree_name)).range([0, width]).padding(0.1);
    const y = d3.scaleLinear().domain([0, d3.max(filteredData, d => d.count)]).nice().range([height, 0]);

    svg
        .append("g")
        .attr("class", "x-axis")
        .attr("transform", `translate(0,${height})`)
        .call(d3.axisBottom(x))
        .selectAll("text")
        .attr("transform", "rotate(-45)")
        .style("text-anchor", "end");

    svg.append("g").attr("class", "y-axis").call(d3.axisLeft(y));

    // Add tooltips to the bars
    svg
        .selectAll("rect")
        .data(filteredData)
        .enter()
        .append("rect")
        .attr("x", d => x(d.tree_name))
        .attr("y", d => y(d.count))
        .attr("width", x.bandwidth())
        .attr("height", d => height - y(d.count))
        .attr("fill", "steelblue")
        .append("title") // Add a title element for tooltips
        .text(d => `${d.tree_name}: ${d.count} trees`);

    // Function to show tooltips when hovering over bars
    const tooltip = d3
        .select("body")
        .append("div")
        .attr("class", "tooltip")
        .style("opacity", 0);

    svg
        .selectAll("rect")
        .on("mouseover", function (event, d) {
            tooltip.transition().duration(200).style("opacity", 0.9);
            tooltip.html(`${d.tree_name}: ${d.count} trees`)
                .style("left", (event.pageX) + "px")
                .style("top", (event.pageY - 28) + "px");
        })
        .on("mouseout", function (d) {
            tooltip.transition().duration(500).style("opacity", 0);
        });
}

// Initial render
drawBarChart(uniqueCities[0]);

// Handle dropdown change
cityDropdown.on("change", function () {
    const selectedCity = d3.select(this).property("value");
    drawBarChart(selectedCity);
});



// Create a function to draw the stacked bar chart based on the selected number of cities
function drawStackedBarChart(numCities) {
    const topCities = uniqueCities.slice(0, numCities);
    const filteredData = data.filter(d => topCities.includes(d.city));

    // Group the data by tree_name within each city
    const groupedData = d3.group(filteredData, d => d.city, d => d.tree_name);

    // Get the top 5 tree names with the highest counts for each city
    const cityTopTrees = new Map();
    topCities.forEach(city => {
        const treeCounts = Array.from(groupedData.get(city), ([tree, counts]) => ({
            tree: tree,
            count: d3.sum(counts, d => d.count)
        }));
        treeCounts.sort((a, b) => b.count - a.count);
        cityTopTrees.set(city, treeCounts.slice(0, 5));
    });

    const margin = { top: 20, right: 20, bottom: 60, left: 60 };
    const width = 800 - margin.left - margin.right;
    const height = 400 - margin.top - margin.bottom;

    d3.select("#stackedChart").html("");

    const svg = d3
        .select("#stackedChart")
        .append("svg")
        .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

    const x = d3.scaleBand().domain(topCities).range([0, width]).padding(0.1);
    const y = d3.scaleLinear().domain([0, d3.max(cityTopTrees.get(topCities[0]), d => d.count)]).nice().range([height, 0]);

    const color = d3.scaleOrdinal(d3.schemeCategory10);

    // Create a group for each tree name
    const groups = svg.selectAll("g")
        .data(topCities)
        .enter()
        .append("g")
        .attr("transform", d => `translate(${x(d)},0)`);

    // Create a bar for each tree name within the group
    groups.selectAll("rect")
        .data(d => cityTopTrees.get(d))
        .enter()
        .append("rect")
        .attr("x", d => x(d.city))
        .attr("y", d => y(d.count))
        .attr("width", x.bandwidth())
        .attr("height", d => height - y(d.count))
        .attr("fill", d => color(d.tree))
        .append("title")
        .text(d => `${d.city}: ${d.tree} - ${d.count} trees`);

    // Create the x-axis
    svg.append("g")
        .attr("class", "x-axis")
        .attr("transform", `translate(0,${height})`)
        .call(d3.axisBottom(x));

    // Create the y-axis
    svg.append("g")
        .attr("class", "y-axis")
        .call(d3.axisLeft(y));


}
drawStackedBarChart(5);
// Handle dropdown change for the number of cities
d3.select("#numCitiesSelection").on("change", function () {
    const selectedNumCities = d3.select(this).property("value");
    drawStackedBarChart(parseInt(selectedNumCities));
    
});

// Sample data in JSON format
const data1 = [{
  city: "Anaheim",
  tree: "Platanus acerifolia",
  count: 0
},
{
  city: "Anaheim",
  tree: "Magnolia grandiflora",
  count: 5087
},
{
  city: "Anaheim",
  tree: "Washingtonia robusta",
  count: 3515
},
{
  city: "Anaheim",
  tree: "Syagrus romanzoffianum",
  count: 1551
},
{
  city: "Anaheim",
  tree: "Liquidambar styraciflua",
  count: 1471
},
{
  city: "Oakland",
  tree: "Liquidambar styraciflua",
  count: 2397
},
{
  city: "Oakland",
  tree: "Platanus acerifolia",
  count: 1940
},
{
  city: "Oakland",
  tree: "Magnolia grandiflora",
  count: 978
},
{
  city: "Oakland",
  tree: "Syagrus romanzoffianum",
  count: 0
},
{
  city: "Oakland",
  tree: "Washingtonia robusta",
  count: 0
},
{
  city: "Sacramento",
  tree: "Platanus acerifolia",
  count: 14111
},
{
  city: "Sacramento",
  tree: "Syagrus romanzoffianum",
  count: 0
},
{
  city: "Sacramento",
  tree: "Washingtonia robusta",
  count: 0
},
{
  city: "Sacramento",
  tree: "Magnolia grandiflora",
  count: 0
},
{
  city: "Sacramento",
  tree: "Liquidambar styraciflua",
  count: 1933
},
{
  city: "San Diego",
  tree: "Syagrus romanzoffianum",
  count: 22624
},
{
  city: "San Diego",
  tree: "Magnolia grandiflora",
  count: 0
},
{
  city: "San Diego",
  tree: "Platanus acerifolia",
  count: 0
},
{
  city: "San Diego",
  tree: "Washingtonia robusta",
  count: 15129
},
{
  city: "San Diego",
  tree: "Liquidambar styraciflua",
  count: 10323
},
{
  city: "San Francisco",
  tree: "Platanus acerifolia",
  count: 11925
},
{
  city: "San Francisco",
  tree: "Liquidambar styraciflua",
  count: 0
},
{
  city: "San Francisco",
  tree: "Syagrus romanzoffianum",
  count: 0
},
{
  city: "San Francisco",
  tree: "Washingtonia robusta",
  count: 0
},
{
  city: "San Francisco",
  tree: "Magnolia grandiflora",
  count: 7793
}];


// Define the dimensions and margins for the heatmap
const margin = { top: 20, right: 20, bottom: 60, left: 60 };
const width = 1300 - margin.left - margin.right;
const height = 520 - margin.top - margin.bottom;

// Create an SVG element
const svg = d3.select('#heatmap')
  .append('svg')
  .attr("width", width + margin.left + margin.right)
        .attr("height", height + margin.top + margin.bottom)
        .append("g")
        .attr("transform", `translate(${margin.left},${margin.top})`);

// Create scales for X and Y axes
const cities = Array.from(new Set(data1.map(d => d.city)));
const trees = Array.from(new Set(data1.map(d => d.tree)));

const xScale = d3.scaleBand()
  .domain(cities)
  .range([margin.left, width - margin.right])
  .padding(0.2);

const yScale = d3.scaleBand()
  .domain(trees)
  .range([height - margin.bottom, margin.top])
  .padding(0.2);

// Create a color scale based on the tree count
const colorScale = d3.scaleSequential(d3.interpolateBlues)
  .domain([10, d3.max(data1, d => d.count)*1.5]);

// Create and append heatmap cells
svg.selectAll()
  .data(data1)
  .enter()
  .append('rect')
  .attr('x', d => xScale(d.city))
  .attr('y', d => yScale(d.tree))
  .attr('width', xScale.bandwidth())
  .attr('height', yScale.bandwidth())
  .style('fill', d => colorScale(d.count));

// Add X and Y axes
const xAxis = d3.axisBottom(xScale);
const yAxis = d3.axisLeft(yScale);

svg.append('g')
  .attr('class', 'x-axis')
  .attr('transform', `translate(0, ${height - margin.bottom})`)
  .call(xAxis);

svg.append('g')
  .attr('class', 'y-axis')
  .attr('transform', `translate(${margin.left}, 0)`)
  .call(yAxis);


